const soundDatabase = {
    animals: {
        title: "Animals", icon: "🐾", subtitle: "Hear how animals speak around the world! ✨",
        data: {
            dog: { id: 'dog', icon: "🐶", name: "Dog", params: { pitch: 1, rate: 1.1 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Woof", pron: "woof", native: "woof", fallback: "woof" },
                { country: "Korea", flag: "🇰🇷", sound: "멍멍", pron: "mung-mung", native: "멍멍", fallback: "mung mung" },
                { country: "Japan", flag: "🇯🇵", sound: "ワンワン", pron: "wan-wan", native: "ワンワン", fallback: "wahn wahn" },
                { country: "Spain", flag: "🇪🇸", sound: "Guau", pron: "gwah-oo", native: "guau", fallback: "gwah oo" },
                { country: "France", flag: "🇫🇷", sound: "Ouah ouah", pron: "wah-wah", native: "ouah ouah", fallback: "wah wah" },
                { country: "Germany", flag: "🇩🇪", sound: "Wuff", pron: "voof", native: "wuff", fallback: "voof" },
                { country: "Italy", flag: "🇮🇹", sound: "Bau bau", pron: "bow-bow", native: "bau bau", fallback: "bow bow" },
                { country: "Russia", flag: "🇷🇺", sound: "Гав-гав", pron: "gahv-gahv", native: "гав гав", fallback: "gahv gahv" },
                { country: "Thailand", flag: "🇹🇭", sound: "โฮ่งโฮ่ง", pron: "hohng-hohng", native: "โฮ่งโฮ่ง", fallback: "hoahng hoahng" },
                { country: "Egypt", flag: "🇪🇬", sound: "هوهو", pron: "haw-haw", native: "هوهو", fallback: "haw-haw" },
                { country: "Brazil", flag: "🇧🇷", sound: "Au au", pron: "ow-ow", native: "au au", fallback: "ow ow" },
                { country: "China", flag: "🇨🇳", sound: "汪汪", pron: "wahng-wahng", native: "汪汪", fallback: "wahng wahng" },
                { country: "India", flag: "🇮🇳", sound: "भौ-भौ", pron: "bhow-bhow", native: "भौ-भौ", fallback: "bhow bhow" },
                { country: "Kenya", flag: "🇰🇪", sound: "Bwe bwe", pron: "bweh-bweh", native: "bwe bwe", fallback: "bweh bweh" },
                { country: "Greece", flag: "🇬🇷", sound: "Γαβ γαβ", pron: "gahv-gahv", native: "γαβ γαβ", fallback: "gahv gahv" }
            ]},
            cat: { id: 'cat', icon: "🐱", name: "Cat", params: { pitch: 1.2, rate: 1.1 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Meow", pron: "mee-ow", native: "meow", fallback: "meow" },
                { country: "Korea", flag: "🇰🇷", sound: "야옹", pron: "yah-ohng", native: "야옹", fallback: "yah-ohng" },
                { country: "Japan", flag: "🇯🇵", sound: "ニャー", pron: "nyah", native: "ニャー", fallback: "nyah" },
                { country: "Spain", flag: "🇪🇸", sound: "Miau", pron: "mee-ow", native: "miau", fallback: "mee ow" },
                { country: "France", flag: "🇫🇷", sound: "Miaou", pron: "mee-ow", native: "miaou", fallback: "mee ow" },
                { country: "Germany", flag: "🇩🇪", sound: "Miau", pron: "mee-ow", native: "miau", fallback: "mee ow" },
                { country: "Italy", flag: "🇮🇹", sound: "Miao", pron: "mee-ow", native: "miao", fallback: "mee ow" },
                { country: "Russia", flag: "🇷🇺", sound: "Мяу", pron: "myaw", native: "мяу", fallback: "myaw" },
                { country: "Thailand", flag: "🇹🇭", sound: "เหมียว", pron: "mee-ow", native: "เหมียว", fallback: "meee ow" },
                { country: "Egypt", flag: "🇪🇬", sound: "مياو", pron: "mee-yow", native: "مياو", fallback: "mee yow" },
                { country: "Brazil", flag: "🇧🇷", sound: "Miau", pron: "mee-ow", native: "miau", fallback: "mee ow" },
                { country: "China", flag: "🇨🇳", sound: "喵喵", pron: "meow-meow", native: "喵喵", fallback: "meow meow" },
                { country: "India", flag: "🇮🇳", sound: "म्याऊं", pron: "mya-oo", native: "म्याऊं", fallback: "mya oo" },
                { country: "Kenya", flag: "🇰🇪", sound: "Nyau", pron: "nyow", native: "nyau", fallback: "ny-ow" },
                { country: "Greece", flag: "🇬🇷", sound: "Νιάου", pron: "nee-ow", native: "νιάου", fallback: "nee ow" }
            ]},
            rooster: { id: 'rooster', icon: "🐓", name: "Rooster", params: { pitch: 1.1, rate: 1.2 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Cock-a-doo", pron: "cock-a-doo", native: "cock-a-doodle-doo", fallback: "cock-a-doodle-doo" },
                { country: "Korea", flag: "🇰🇷", sound: "꼬끼오", pron: "kko-kkee-oh", native: "꼬끼오", fallback: "kko kkee oh" },
                { country: "Japan", flag: "🇯🇵", sound: "コケコッコー", pron: "ko-ke-kok-koh", native: "コケコッコー", fallback: "ko keh kok koh" },
                { country: "Spain", flag: "🇪🇸", sound: "Quiquiriquí", pron: "kee-kee-ree-kee", native: "quiquiriquí", fallback: "kee kee ree kee" },
                { country: "France", flag: "🇫🇷", sound: "Cocorico", pron: "ko-ko-ree-ko", native: "cocorico", fallback: "ko ko ree ko" },
                { country: "Germany", flag: "🇩🇪", sound: "Kikeriki", pron: "kee-keh-ree-kee", native: "kikeriki", fallback: "kee keh ree kee" },
                { country: "Italy", flag: "🇮🇹", sound: "Chicchirichì", pron: "keek-kee-ree-kee", native: "chicchirichì", fallback: "keek kee ree kee" },
                { country: "Russia", flag: "🇷🇺", sound: "Кукареку", pron: "koo-kah-re-koo", native: "кукареку", fallback: "koo kah re koo" },
                { country: "Thailand", flag: "🇹🇭", sound: "เอกอีเอ้กเอ้ก", pron: "eck-ee-eck-eck", native: "เอกอีเอ้กเอ้ก", fallback: "eck ee eck eck" },
                { country: "Egypt", flag: "🇪🇬", sound: "كوكو كوكو", pron: "koo-koo-koo-koo", native: "كوكو كوكو", fallback: "koo koo koo koo" },
                { country: "Brazil", flag: "🇧🇷", sound: "Cocoricó", pron: "ko-ko-ree-ko", native: "cocoricó", fallback: "ko ko ree ko" },
                { country: "China", flag: "🇨🇳", sound: "喔喔喔", pron: "woh-woh-woh", native: "喔喔喔", fallback: "woh woh woh" },
                { country: "India", flag: "🇮🇳", sound: "कुकड़ू कू", pron: "kook-roo-koo", native: "कुकड़ू कू", fallback: "kook roo koo" },
                { country: "Kenya", flag: "🇰🇪", sound: "Kokoriko", pron: "ko-ko-ree-ko", native: "kokoriko", fallback: "ko ko ree ko" },
                { country: "Greece", flag: "🇬🇷", sound: "Κικιρίκου", pron: "kee-kee-ree-koo", native: "κικιρίκου", fallback: "kee kee ree koo" }
            ]},
            cow: { id: 'cow', icon: "🐮", name: "Cow", params: { pitch: 0.8, rate: 0.8 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Moo", pron: "mooo", native: "moooo", fallback: "moooo" },
                { country: "Korea", flag: "🇰🇷", sound: "음매", pron: "eum-mae", native: "음매", fallback: "eum mae" },
                { country: "Japan", flag: "🇯🇵", sound: "モー", pron: "moah", native: "モー", fallback: "moah" },
                { country: "Spain", flag: "🇪🇸", sound: "Muu", pron: "moooo", native: "muu", fallback: "mooo" },
                { country: "France", flag: "🇫🇷", sound: "Meuh", pron: "muh", native: "meuh", fallback: "muhh" },
                { country: "Germany", flag: "🇩🇪", sound: "Muh", pron: "mooo", native: "muh", fallback: "mooo" },
                { country: "Italy", flag: "🇮🇹", sound: "Muu", pron: "moooo", native: "muu", fallback: "mooo" },
                { country: "Russia", flag: "🇷🇺", sound: "Му", pron: "mooo", native: "му", fallback: "mooo" },
                { country: "Thailand", flag: "🇹🇭", sound: "มอ", pron: "moah", native: "มอ", fallback: "moah" },
                { country: "Egypt", flag: "🇪🇬", sound: "موو", pron: "moooo", native: "موو", fallback: "moooo" },
                { country: "Brazil", flag: "🇧🇷", sound: "Muuu", pron: "moooo", native: "muuu", fallback: "moooo" },
                { country: "China", flag: "🇨🇳", sound: "哞", pron: "moah", native: "哞", fallback: "moah" },
                { country: "India", flag: "🇮🇳", sound: "मूं", pron: "moonn", native: "मूं", fallback: "moonn" },
                { country: "Kenya", flag: "🇰🇪", sound: "Mooo", pron: "moooo", native: "mooo", fallback: "moooo" },
                { country: "Greece", flag: "🇬🇷", sound: "Μου", pron: "mooo", native: "μου", fallback: "mooo" }
            ]},
            pig: { id: 'pig', icon: "🐷", name: "Pig", params: { pitch: 0.9, rate: 1.1 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Oink", pron: "oynk", native: "oink", fallback: "oynk" },
                { country: "Korea", flag: "🇰🇷", sound: "꿀꿀", pron: "kkool-kkool", native: "꿀꿀", fallback: "kkool kkool" },
                { country: "Japan", flag: "🇯🇵", sound: "ブーブー", pron: "booo-booo", native: "ブーブー", fallback: "booo booo" },
                { country: "Spain", flag: "🇪🇸", sound: "Oink", pron: "oynk", native: "oink", fallback: "oynk" },
                { country: "France", flag: "🇫🇷", sound: "Groin groin", pron: "grwah-grwah", native: "groin groin", fallback: "grwah grwah" },
                { country: "Germany", flag: "🇩🇪", sound: "Grunz", pron: "groonz", native: "grunz", fallback: "groonz" },
                { country: "Italy", flag: "🇮🇹", sound: "Oink", pron: "oynk", native: "oink", fallback: "oynk" },
                { country: "Russia", flag: "🇷🇺", sound: "Хрю-хрю", pron: "khryu-khryu", native: "хрю хрю", fallback: "khryu khryu" },
                { country: "Thailand", flag: "🇹🇭", sound: "อู๊드อู๊드", pron: "ood-ood", native: "อู๊드อู๊드", fallback: "ood ood" },
                { country: "Egypt", flag: "🇪🇬", sound: "قبق", pron: "kah-bahk", native: "قبق", fallback: "kah bahk" },
                { country: "Brazil", flag: "🇧🇷", sound: "Oinc oinc", pron: "oynk-oynk", native: "oinc oinc", fallback: "oynk oynk" },
                { country: "China", flag: "🇨🇳", sound: "哼哼", pron: "heng-heng", native: "哼哼", fallback: "heng heng" },
                { country: "India", flag: "🇮🇳", sound: "ओइंक", pron: "oynk", native: "ओइंक", fallback: "oynk" },
                { country: "Kenya", flag: "🇰🇪", sound: "Ngorrr", pron: "ngorr", native: "ngorrr", fallback: "ngorr" },
                { country: "Greece", flag: "🇬🇷", sound: "Γκρρ", pron: "groo-groo", native: "γκρου γκρου", fallback: "groo groo" }
            ]},
            duck: { id: 'duck', icon: "🦆", name: "Duck", params: { pitch: 1.3, rate: 1.1 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Quack", pron: "quack", native: "quack", fallback: "quack" },
                { country: "Korea", flag: "🇰🇷", sound: "꽥꽥", pron: "kkwaek-kkwaek", native: "꽥꽥", fallback: "kkwaek kkwaek" },
                { country: "Japan", flag: "🇯🇵", sound: "ガーガー", pron: "gah-gah", native: "ガーガー", fallback: "gah gah" },
                { country: "Spain", flag: "🇪🇸", sound: "Cuac", pron: "kwahk", native: "cuac", fallback: "kwahk" },
                { country: "France", flag: "🇫🇷", sound: "Coin coin", pron: "kwahn-kwahn", native: "coin coin", fallback: "kwahn kwahn" },
                { country: "Germany", flag: "🇩🇪", sound: "Quack", pron: "kwahk", native: "quack", fallback: "kwahk" },
                { country: "Italy", flag: "🇮🇹", sound: "Qua qua", pron: "kwah-kwah", native: "qua qua", fallback: "kwah kwah" },
                { country: "Russia", flag: "🇷🇺", sound: "Кря-кря", pron: "kryah-kryah", native: "кря кря", fallback: "kryah kryah" },
                { country: "Thailand", flag: "🇹🇭", sound: "ก้าบก้าบ", pron: "gahb-gahb", native: "ก้าบก้าบ", fallback: "gahb gahb" },
                { country: "Egypt", flag: "🇪🇬", sound: "واك واك", pron: "wahk-wahk", native: "واك واك", fallback: "wahk wahk" },
                { country: "Brazil", flag: "🇧🇷", sound: "Quá quá", pron: "kwah-kwah", native: "quá quá", fallback: "kwah kwah" },
                { country: "China", flag: "🇨🇳", sound: "嘎嘎", pron: "gah-gah", native: "嘎嘎", fallback: "gah gah" },
                { country: "India", flag: "🇮🇳", sound: "क्वैक", pron: "quack", native: "क्वैक", fallback: "quack" },
                { country: "Kenya", flag: "🇰🇪", sound: "Kwak kwak", pron: "kwahk-kwahk", native: "kwak kwak", fallback: "kwahk kwahk" },
                { country: "Greece", flag: "🇬🇷", sound: "Πα πα", pron: "pah-pah", native: "πα πα", fallback: "pah pah" }
            ]},
            frog: { id: 'frog', icon: "🐸", name: "Frog", params: { pitch: 0.8, rate: 1.0 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Ribbit", pron: "rih-bit", native: "ribbit", fallback: "rih bit" },
                { country: "Korea", flag: "🇰🇷", sound: "개굴개굴", pron: "gae-gool", native: "개굴개굴", fallback: "gae gool" },
                { country: "Japan", flag: "🇯🇵", sound: "ケロケロ", pron: "keh-ro-keh-ro", native: "ケロケロ", fallback: "keh ro keh ro" },
                { country: "Spain", flag: "🇪🇸", sound: "Croac", pron: "kroh-ahk", native: "croac", fallback: "kroh ahk" },
                { country: "France", flag: "🇫🇷", sound: "Coa coa", pron: "kwah kwah", native: "coa coa", fallback: "kwah kwah" },
                { country: "Germany", flag: "🇩🇪", sound: "Quak", pron: "kwahk", native: "quack", fallback: "kwahk" },
                { country: "Italy", flag: "🇮🇹", sound: "Cra cra", pron: "krah krah", native: "cra cra", fallback: "krah krah" },
                { country: "Russia", flag: "🇷🇺", sound: "Ква-ква", pron: "kvah kvah", native: "ква ква", fallback: "kvah kvah" },
                { country: "Thailand", flag: "🇹🇭", sound: "อ๊บอ๊บ", pron: "ohp ohp", native: "อ๊บอ๊บ", fallback: "ohp ohp" },
                { country: "Egypt", flag: "🇪🇬", sound: "نقيق", pron: "nah keek", native: "نقيق", fallback: "nah keek" },
                { country: "Brazil", flag: "🇧🇷", sound: "Croac", pron: "kroh-ahk", native: "croac", fallback: "kroh ahk" },
                { country: "China", flag: "🇨🇳", sound: "呱呱", pron: "gwah gwah", native: "呱呱", fallback: "gwah gwah" },
                { country: "India", flag: "🇮🇳", sound: "टर्र-टर्र", pron: "tuhrr tuhrr", native: "टर्र-टर्र", fallback: "tuhrr tuhrr" },
                { country: "Kenya", flag: "🇰🇪", sound: "Kora", pron: "ko rah", native: "kora", fallback: "ko rah" },
                { country: "Greece", flag: "🇬🇷", sound: "Κουάξ", pron: "koo ahks", native: "κουάξ", fallback: "koo ahks" }
            ]},
            horse: { id: 'horse', icon: "🐴", name: "Horse", params: { pitch: 1.1, rate: 1.3 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Neigh", pron: "nay", native: "neigh", fallback: "nay" },
                { country: "Korea", flag: "🇰🇷", sound: "히잉", pron: "hee-ing", native: "히잉", fallback: "hee ing" },
                { country: "Japan", flag: "🇯🇵", sound: "ヒヒーン", pron: "hee-hee-een", native: "ヒヒーン", fallback: "hee hee een" },
                { country: "Spain", flag: "🇪🇸", sound: "Hiii", pron: "heee", native: "hiii", fallback: "heee" },
                { country: "France", flag: "🇫🇷", sound: "Hiiii", pron: "heee", native: "hiii", fallback: "heee" },
                { country: "Germany", flag: "🇩🇪", sound: "Wiehern", pron: "vee-hern", native: "wiehern", fallback: "vee hern" },
                { country: "Italy", flag: "🇮🇹", sound: "Ihii", pron: "ee-heee", native: "ihii", fallback: "ee heee" },
                { country: "Russia", flag: "🇷🇺", sound: "Иго-го", pron: "ee-go-go", native: "иго-го", fallback: "ee go go" },
                { country: "Thailand", flag: "🇹🇭", sound: "ฮี้", pron: "heee", native: "ฮี้", fallback: "heee" },
                { country: "Egypt", flag: "🇪🇬", sound: "صهيل", pron: "sah-heel", native: "صهيل", fallback: "sah heel" },
                { country: "Brazil", flag: "🇧🇷", sound: "Hiiiii", pron: "heeee", native: "hiiiii", fallback: "heeee" },
                { country: "China", flag: "🇨🇳", sound: "嘶", pron: "seee", native: "嘶", fallback: "seee" },
                { country: "India", flag: "🇮🇳", sound: "हिनहिनाना", pron: "heen-hee-nah", native: "हिनहिना나", fallback: "heen heen" },
                { country: "Kenya", flag: "🇰🇪", sound: "Ngg'hiii", pron: "hee-eee", native: "ngg'hiii", fallback: "heeee" },
                { country: "Greece", flag: "🇬🇷", sound: "Ιιι", pron: "eeee", native: "ιιι", fallback: "eeee" }
            ]},
            sheep: { id: 'sheep', icon: "🐑", name: "Sheep", params: { pitch: 1.2, rate: 0.9 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Baa", pron: "baah", native: "baah", fallback: "baah" },
                { country: "Korea", flag: "🇰🇷", sound: "메에", pron: "meh-ae", native: "메에", fallback: "meh ae" },
                { country: "Japan", flag: "🇯🇵", sound: "メー", pron: "meee", native: "メー", fallback: "meee" },
                { country: "Spain", flag: "🇪🇸", sound: "Bee", pron: "beee", native: "bee", fallback: "beee" },
                { country: "France", flag: "🇫🇷", sound: "Bêê", pron: "behh", native: "bêê", fallback: "behh" },
                { country: "Germany", flag: "🇩🇪", sound: "Mäh", pron: "mahh", native: "mäh", fallback: "mahh" },
                { country: "Italy", flag: "🇮🇹", sound: "Bee", pron: "beee", native: "bee", fallback: "beee" },
                { country: "Russia", flag: "🇷🇺", sound: "Бе-е", pron: "beh-ae", native: "бе е", fallback: "beh ae" },
                { country: "Thailand", flag: "🇹🇭", sound: "แบะแบะ", pron: "beh-beh", native: "แบะแบะ", fallback: "beh beh" },
                { country: "Egypt", flag: "🇪🇬", sound: "ماع", pron: "maaa", native: "ماع", fallback: "maaa" },
                { country: "Brazil", flag: "🇧🇷", sound: "Béé", pron: "beeeh", native: "béé", fallback: "beeeh" },
                { country: "China", flag: "🇨🇳", sound: "咩", pron: "mee-ae", native: "咩", fallback: "mee ae" },
                { country: "India", flag: "🇮🇳", sound: "बा-바", pron: "baah-baah", native: "बा-바", fallback: "baah baah" },
                { country: "Kenya", flag: "🇰🇪", sound: "Meee", pron: "meee", native: "meee", fallback: "meee" },
                { country: "Greece", flag: "🇬🇷", sound: "Μπε", pron: "beh", native: "μπε", fallback: "beh" }
            ]},
            mouse: { id: 'mouse', icon: "🐭", name: "Mouse", params: { pitch: 1.6, rate: 1.3 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Squeak", pron: "skweek", native: "squeak", fallback: "skweek" },
                { country: "Korea", flag: "🇰🇷", sound: "찍찍", pron: "jjik-jjik", native: "찍찍", fallback: "jjik jjik" },
                { country: "Japan", flag: "🇯🇵", sound: "チューチュー", pron: "choo-choo", native: "チューチュー", fallback: "choo choo" },
                { country: "Spain", flag: "🇪🇸", sound: "Cui-cui", pron: "quee-quee", native: "quee quee", fallback: "quee quee" },
                { country: "France", flag: "🇫🇷", sound: "Couic", pron: "kweek", native: "couic", fallback: "kweek" },
                { country: "Germany", flag: "🇩🇪", sound: "Piep", pron: "peeep", native: "piep", fallback: "peeep" },
                { country: "Italy", flag: "🇮🇹", sound: "Squit", pron: "skwit", native: "squit", fallback: "skweet" },
                { country: "Russia", flag: "🇷🇺", sound: "Пи-пи", pron: "pee-pee", native: "пи пи", fallback: "pee pee" },
                { country: "Thailand", flag: "🇹🇭", sound: "จี๊드", pron: "jeed", native: "จี๊드จี๊드", fallback: "jeed" },
                { country: "Egypt", flag: "🇪🇬", sound: "صرير", pron: "sah-reer", native: "صرير", fallback: "sah reer" },
                { country: "Brazil", flag: "🇧🇷", sound: "Squeak", pron: "skweek", native: "squeak", fallback: "skweek" },
                { country: "China", flag: "🇨🇳", sound: "吱吱", pron: "jee-jee", native: "吱吱", fallback: "jee jee" },
                { country: "India", flag: "🇮🇳", sound: "चीं-चीं", pron: "chee-chee", native: "चीं-चीं", fallback: "chee chee" },
                { country: "Kenya", flag: "🇰🇪", sound: "Nji nji", pron: "nyee-nyee", native: "nji nji", fallback: "nyee nyee" },
                { country: "Greece", flag: "🇬🇷", sound: "Σκουίκ", pron: "skoo-eek", native: "σκουίκ", fallback: "skoo eek" }
            ]},
            elephant: { id: 'elephant', icon: "🐘", name: "Elephant", params: { pitch: 0.6, rate: 0.7 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Toot", pron: "tooot", native: "tooot", fallback: "tooot" },
                { country: "Korea", flag: "🇰🇷", sound: "뿌우", pron: "ppoo-oo", native: "뿌우", fallback: "ppoo oo" },
                { country: "Japan", flag: "🇯🇵", sound: "パオーン", pron: "pah-oah-n", native: "パオーン", fallback: "pah oahn" },
                { country: "Spain", flag: "🇪🇸", sound: "Barritar", pron: "bah-ree-tar", native: "barritar", fallback: "bah ree tar" },
                { country: "France", flag: "🇫🇷", sound: "Barrir", pron: "bah-reer", native: "barrir", fallback: "bah reer" },
                { country: "Germany", flag: "🇩🇪", sound: "Töröö", pron: "tuhr-uh-uh", native: "tuhr-uh-uh", fallback: "tuhr uh uh" },
                { country: "Italy", flag: "🇮🇹", sound: "Barrito", pron: "bah-ree-toe", native: "barrito", fallback: "bah ree toe" },
                { country: "Russia", flag: "🇷🇺", sound: "Труту", pron: "troo-too", native: "труту", fallback: "troo too" },
                { country: "Thailand", flag: "🇹🇭", sound: "แปร๊น", pron: "prah-en", native: "แปร๊น", fallback: "prah en" },
                { country: "Egypt", flag: "🇪🇬", sound: "بوق", pron: "boook", native: "بوق", fallback: "boook" },
                { country: "Brazil", flag: "🇧🇷", sound: "Fuuu", pron: "foooo", native: "fuuu", fallback: "fooo" },
                { country: "China", flag: "🇨🇳", sound: "昂", pron: "ah-ng", native: "昂", fallback: "ah ng" },
                { country: "India", flag: "🇮🇳", sound: "चिंघाड़", pron: "ching-hah-rd", native: "चिंघाड़", fallback: "ching hah" },
                { country: "Kenya", flag: "🇰🇪", sound: "Pwweeh", pron: "pwweh", native: "pwweeh", fallback: "pwweh" },
                { country: "Greece", flag: "🇬🇷", sound: "Τουου", pron: "tooo", native: "τουου", fallback: "tooo" }
            ]},
            lion: { id: 'lion', icon: "🦁", name: "Lion", params: { pitch: 0.5, rate: 0.8 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Roar", pron: "rawhr", native: "roar", fallback: "rawhr" },
                { country: "Korea", flag: "🇰🇷", sound: "어흥", pron: "uh-heung", native: "어흥", fallback: "uh heung" },
                { country: "Japan", flag: "🇯🇵", sound: "ガオー", pron: "gah-oah", native: "ガオー", fallback: "gah oah" },
                { country: "Spain", flag: "🇪🇸", sound: "Grrr", pron: "grrrr", native: "grrr", fallback: "grrr" },
                { country: "France", flag: "🇫🇷", sound: "Roar", pron: "rawhr", native: "roar", fallback: "rawhr" },
                { country: "Germany", flag: "🇩🇪", sound: "Roar", pron: "rawhr", native: "roar", fallback: "rawhr" },
                { country: "Italy", flag: "🇮🇹", sound: "Grrr", pron: "grrrr", native: "grrr", fallback: "grrr" },
                { country: "Russia", flag: "🇷🇺", sound: "Р-р-р", pron: "rrrr", native: "р р р", fallback: "rrrr" },
                { country: "Thailand", flag: "🇹🇭", sound: "โฮก", pron: "hoah-k", native: "โฮก", fallback: "hoahk" },
                { country: "Egypt", flag: "🇪🇬", sound: "زئير", pron: "zah-eer", native: "زئير", fallback: "zah eer" },
                { country: "Brazil", flag: "🇧🇷", sound: "Roar", pron: "rawhr", native: "roar", fallback: "rawhr" },
                { country: "China", flag: "🇨🇳", sound: "吼", pron: "hoah", native: "吼", fallback: "hoah" },
                { country: "India", flag: "🇮🇳", sound: "दहाड़", pron: "dah-hah-rd", native: "दहाड़", fallback: "dah hahr" },
                { country: "Kenya", flag: "🇰🇪", sound: "Rrrrr", pron: "rrrr", native: "rrrrr", fallback: "rrrr" },
                { country: "Greece", flag: "🇬🇷", sound: "Γκρρ", pron: "grrr", native: "γκρρ", fallback: "grrr" }
            ]},
            monkey: { id: 'monkey', icon: "🐒", name: "Monkey", params: { pitch: 1.4, rate: 1.4 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Ooh aah", pron: "oo-oo-ah-ah", native: "ooh ooh aah aah", fallback: "ooh ooh aah aah" },
                { country: "Korea", flag: "🇰🇷", sound: "우끼끼", pron: "oo-kkee-kkee", native: "우끼끼", fallback: "oo kkee kkee" },
                { country: "Japan", flag: "🇯🇵", sound: "ウ키키", pron: "oo-kee-kee", native: "ウ키키", fallback: "oo kee kee" },
                { country: "Spain", flag: "🇪🇸", sound: "Uu aa", pron: "oo-ah", native: "oo aa", fallback: "oo ah" },
                { country: "France", flag: "🇫🇷", sound: "Ouh ouh", pron: "oo-oo-ah-ah", native: "ouh ouh", fallback: "oo oo" },
                { country: "Germany", flag: "🇩🇪", sound: "Uu aa", pron: "oo-ah", native: "uu aa", fallback: "oo ah" },
                { country: "Italy", flag: "🇮🇹", sound: "Uu aa", pron: "oo-ah", native: "uu aa", fallback: "oo ah" },
                { country: "Russia", flag: "🇷🇺", sound: "У-а-а", pron: "oo-ah-ah", native: "у а а", fallback: "oo ah ah" },
                { country: "Thailand", flag: "🇹🇭", sound: "เจี๊ยก", pron: "je-ack", native: "เจี๊ยกเจี๊ยก", fallback: "je-ack" },
                { country: "Egypt", flag: "🇪🇬", sound: "قرد", pron: "keerd", native: "قرد", fallback: "keerd" },
                { country: "Brazil", flag: "🇧🇷", sound: "Uh uh", pron: "oo-oo-ah-ah", native: "uh uh", fallback: "uh uh" },
                { country: "China", flag: "🇨🇳", sound: "叽叽", pron: "jee-jee", native: "叽叽", fallback: "jee jee" },
                { country: "India", flag: "🇮🇳", sound: "खो-खो", pron: "kho-kho", native: "खो-खो", fallback: "kho kho" },
                { country: "Kenya", flag: "🇰🇪", sound: "Khee khee", pron: "khee-khee", native: "khee khee", fallback: "khee khee" },
                { country: "Greece", flag: "🇬🇷", sound: "Ου ου α α", pron: "oo-oo-ah-ah", native: "ου ου α α", fallback: "oo ah ah" }
            ]},
            owl: { id: 'owl', icon: "🦉", name: "Owl", params: { pitch: 0.7, rate: 0.9 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Hoot", pron: "hooat", native: "hoot", fallback: "hooat" },
                { country: "Korea", flag: "🇰🇷", sound: "부엉부엉", pron: "boo-uhng", native: "부엉부엉", fallback: "boo uhng" },
                { country: "Japan", flag: "🇯🇵", sound: "ホーホー", pron: "hoh-hoh", native: "ホーホー", fallback: "hoh hoh" },
                { country: "Spain", flag: "🇪🇸", sound: "Uu uu", pron: "oo-oo", native: "uu uu", fallback: "oo oo" },
                { country: "France", flag: "🇫🇷", sound: "Hou hou", pron: "oo-oo", native: "hou hou", fallback: "oo oo" },
                { country: "Germany", flag: "🇩🇪", sound: "Uhu", pron: "oo-hoo", native: "uhu", fallback: "oo hoo" },
                { country: "Italy", flag: "🇮🇹", sound: "Hu hu", pron: "hoo-hoo", native: "hu hu", fallback: "hoo hoo" },
                { country: "Russia", flag: "🇷🇺", sound: "Уху", pron: "oo-hoo", native: "уху", fallback: "oo hoo" },
                { country: "Thailand", flag: "🇹🇭", sound: "ฮูก", pron: "hook", native: "ฮูกฮูก", fallback: "hook" },
                { country: "Egypt", flag: "🇪🇬", sound: "هوو هو", pron: "hooo-hooo", native: "هوو هو", fallback: "hooo hooo" },
                { country: "Brazil", flag: "🇧🇷", sound: "Uhu", pron: "oo-hoo", native: "uhu", fallback: "oo hoo" },
                { country: "China", flag: "🇨🇳", sound: "咕咕", pron: "goo-goo", native: "咕咕", fallback: "goo goo" },
                { country: "India", flag: "🇮🇳", sound: "हू-हू", pron: "hooo-hooo", native: "हू-हू", fallback: "hooo hooo" },
                { country: "Kenya", flag: "🇰🇪", sound: "Hu hu", pron: "hoo-hoo", native: "hu hu", fallback: "hoo hoo" },
                { country: "Greece", flag: "🇬🇷", sound: "Χου χου", pron: "hoo-hoo", native: "χου χου", fallback: "hoo hoo" }
            ]},
            bee: { id: 'bee', icon: "🐝", name: "Bee", params: { pitch: 1.8, rate: 1.5 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Buzz", pron: "buzzzz", native: "buzz", fallback: "buzz" },
                { country: "Korea", flag: "🇰🇷", sound: "윙윙", pron: "wing-wing", native: "윙윙", fallback: "weeng weeng" },
                { country: "Japan", flag: "🇯🇵", sound: "ブーン", pron: "booo-n", native: "ブーン", fallback: "boon" },
                { country: "Spain", flag: "🇪🇸", sound: "Bzz", pron: "bzzzzz", native: "bzz", fallback: "bzzz" },
                { country: "France", flag: "🇫🇷", sound: "Bzz", pron: "bzzzzz", native: "bzz", fallback: "bzzz" },
                { country: "Germany", flag: "🇩🇪", sound: "Summ summ", pron: "zoom-zoom", native: "summ summ", fallback: "zoom zoom" },
                { country: "Italy", flag: "🇮🇹", sound: "Bzz", pron: "bzzzzz", native: "bzz", fallback: "bzzz" },
                { country: "Russia", flag: "🇷🇺", sound: "Жжж", pron: "zhzhzh", native: "ж ж ж", fallback: "zh zh zh" },
                { country: "Thailand", flag: "🇹🇭", sound: "หึ่งหึ่ง", pron: "heung-heung", native: "หึ่งหึ่ง", fallback: "heung heung" },
                { country: "Egypt", flag: "🇪🇬", sound: "طنين", pron: "tah-neen", native: "طنين", fallback: "tah neen" },
                { country: "Brazil", flag: "🇧🇷", sound: "Bzzzz", pron: "bzzzzz", native: "bzz", fallback: "bzzz" },
                { country: "China", flag: "🇨🇳", sound: "嗡嗡", pron: "weng-weng", native: "嗡嗡", fallback: "weng weng" },
                { country: "India", flag: "🇮🇳", sound: "भिन-भिन", pron: "bheen-bheen", native: "भिन-भिन", fallback: "bheen bheen" },
                { country: "Kenya", flag: "🇰🇪", sound: "Zzzzz", pron: "zzzzzz", native: "zzzz", fallback: "zzzz" },
                { country: "Greece", flag: "🇬🇷", sound: "Μζζ", pron: "mzzzzz", native: "μζζ", fallback: "mzzz" }
            ]},
            snake: { id: 'snake', icon: "🐍", name: "Snake", params: { pitch: 1.0, rate: 0.6 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Hiss", pron: "hisss", native: "hisss", fallback: "hisss" },
                { country: "Korea", flag: "🇰🇷", sound: "쉭쉭", pron: "shwik", native: "쉭쉭", fallback: "shwik" },
                { country: "Japan", flag: "🇯🇵", sound: "シャー", pron: "shaah", native: "シャー", fallback: "shaah" },
                { country: "Spain", flag: "🇪🇸", sound: "Sss", pron: "sssss", native: "sss", fallback: "ssss" },
                { country: "France", flag: "🇫🇷", sound: "Sss", pron: "sssss", native: "sss", fallback: "ssss" },
                { country: "Germany", flag: "🇩🇪", sound: "Sss", pron: "sssss", native: "sss", fallback: "ssss" },
                { country: "Italy", flag: "🇮🇹", sound: "Sss", pron: "sssss", native: "sss", fallback: "ssss" },
                { country: "Russia", flag: "🇷🇺", sound: "Ш-ш-ш", pron: "shhhh", native: "ш ш ш", fallback: "shhhh" },
                { country: "Thailand", flag: "🇹🇭", sound: "ฟ่อฟ่อ", pron: "foah-foah", native: "ฟ่อฟ่อ", fallback: "foah foah" },
                { country: "Egypt", flag: "🇪🇬", sound: "فحيح", pron: "fah-heeh", native: "فحيح", fallback: "fah heeh" },
                { country: "Brazil", flag: "🇧🇷", sound: "Sssss", pron: "sssss", native: "ssss", fallback: "ssss" },
                { country: "China", flag: "🇨🇳", sound: "嘶嘶", pron: "seee-seee", native: "嘶嘶", fallback: "seee seee" },
                { country: "India", flag: "🇮🇳", sound: "फुफकार", pron: "foo-foo-kah", native: "फुफकार", fallback: "foo foo" },
                { country: "Kenya", flag: "🇰🇪", sound: "Sssss", pron: "sssss", native: "ssss", fallback: "ssss" },
                { country: "Greece", flag: "🇬🇷", sound: "Σςς", pron: "sssss", native: "σσσ", fallback: "sss" }
            ]}
        }
    },
    objects: {
        title: "Objects", icon: "🚗", subtitle: "How do things sound around the world? 🔔",
        data: {
            car: { id: 'car', icon: "🚗", name: "Car Horn", params: { pitch: 1, rate: 1.2 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Beep beep", pron: "beep-beep", native: "beep beep", fallback: "beep beep" },
                { country: "Korea", flag: "🇰🇷", sound: "빵빵", pron: "ppahng", native: "빵빵", fallback: "ppahng ppahng" },
                { country: "Japan", flag: "🇯🇵", sound: "プップー", pron: "poop-pooo", native: "プップー", fallback: "poo-p poo-p" },
                { country: "Spain", flag: "🇪🇸", sound: "Pi pi", pron: "pee peee", native: "pi pi", fallback: "pee peee" },
                { country: "France", flag: "🇫🇷", sound: "Tut-tut", pron: "toot-toot", native: "tut tut", fallback: "toot toot" },
                { country: "Germany", flag: "🇩🇪", sound: "Tuut tuut", pron: "toot-toot", native: "tuut tuut", fallback: "toot toot" },
                { country: "Italy", flag: "🇮🇹", sound: "Bi bi", pron: "bee-bee", native: "bi bi", fallback: "bee bee" },
                { country: "Russia", flag: "🇷🇺", sound: "Би-би", pron: "bee-bee", native: "би би", fallback: "bee bee" },
                { country: "Thailand", flag: "🇹🇭", sound: "ปี๊นปี๊น", pron: "peen-peen", native: "ปี๊นปี๊น", fallback: "peen peen" },
                { country: "Egypt", flag: "🇪🇬", sound: "بيب بيب", pron: "beep-beep", native: "بيب بيب", fallback: "beep beep" },
                { country: "Brazil", flag: "🇧🇷", sound: "Bi bi", pron: "bee-bee", native: "bi bi", fallback: "bee bee" },
                { country: "China", flag: "🇨🇳", sound: "嘀嘀", pron: "dee-dee", native: "嘀嘀", fallback: "dee dee" },
                { country: "India", flag: "🇮🇳", sound: "पों-पों", pron: "pohn-pohn", native: "पों-पों", fallback: "pohn pohn" },
                { country: "Kenya", flag: "🇰🇪", sound: "Beep beep", pron: "beep-beep", native: "beep beep", fallback: "beep beep" },
                { country: "Greece", flag: "🇬🇷", sound: "Μπιπ μπιπ", pron: "beep-beep", native: "μπιπ μπιπ", fallback: "beep-beep" }
            ]},
            knock: { id: 'knock', icon: "🚪", name: "Door Knock", params: { pitch: 0.8, rate: 1.1 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Knock knock", pron: "knock-knock", native: "knock knock", fallback: "knock knock" },
                { country: "Korea", flag: "🇰🇷", sound: "똑똑", pron: "ttok-ttok", native: "똑똑", fallback: "ttok ttok" },
                { country: "Japan", flag: "🇯🇵", sound: "トントン", pron: "toahn-toahn", native: "トントン", fallback: "toahn toahn" },
                { country: "Spain", flag: "🇪🇸", sound: "Tras tras", pron: "trahs-trahs", native: "tras tras", fallback: "trahs trahs" },
                { country: "France", flag: "🇫🇷", sound: "Toc toc", pron: "toak-toak", native: "toc toc", fallback: "toak toak" },
                { country: "Germany", flag: "🇩🇪", sound: "Klopf klopf", pron: "klopf", native: "klopf klopf", fallback: "klopf klopf" },
                { country: "Italy", flag: "🇮🇹", sound: "Toc toc", pron: "toak-toak", native: "toc toc", fallback: "toak toak" },
                { country: "Russia", flag: "🇷🇺", sound: "Тук-тук", pron: "took-took", native: "тук тук", fallback: "took took" },
                { country: "Thailand", flag: "🇹🇭", sound: "ก๊อกก๊อก", pron: "goak-goak", native: "ก๊อกก๊อก", fallback: "goak goak" },
                { country: "Egypt", flag: "🇪🇬", sound: "طق طق", pron: "tahk-tahk", native: "طق طق", fallback: "tahk tahk" },
                { country: "Brazil", flag: "🇧🇷", sound: "Toc toc", pron: "toak-toak", native: "toc toc", fallback: "toak toak" },
                { country: "China", flag: "🇨🇳", sound: "咚咚", pron: "doahng", native: "咚咚", fallback: "doahng" },
                { country: "India", flag: "🇮🇳", sound: "खट-खट", pron: "khat-khat", native: "खट-खट", fallback: "khat khat" },
                { country: "Kenya", flag: "🇰🇪", sound: "Hodi hodi", pron: "ho-dee", native: "hodi hodi", fallback: "ho dee" },
                { country: "Greece", flag: "🇬🇷", sound: "Τοκ τοκ", pron: "toak-toak", native: "τοκ τοκ", fallback: "toak-toak" }
            ]},
            clock: { id: 'clock', icon: "⏰", name: "Clock", params: { pitch: 1.1, rate: 1 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Tick tock", pron: "tick-tock", native: "tick tock", fallback: "tick tock" },
                { country: "Korea", flag: "🇰🇷", sound: "똑딱똑딱", pron: "ttok-ttak", native: "똑딱똑딱", fallback: "ttok ttak" },
                { country: "Japan", flag: "🇯🇵", sound: "チクタク", pron: "chee-koo", native: "チクタク", fallback: "chee koo" },
                { country: "Spain", flag: "🇪🇸", sound: "Tic tac", pron: "teek-tahk", native: "tic tac", fallback: "teek tahk" },
                { country: "France", flag: "🇫🇷", sound: "Tic tac", pron: "teek-tahk", native: "tic tac", fallback: "teek tahk" },
                { country: "Germany", flag: "🇩🇪", sound: "Tick tack", pron: "teek-tahk", native: "tick tack", fallback: "teek tahk" },
                { country: "Italy", flag: "🇮🇹", sound: "Tic tac", pron: "teek-tahk", native: "tic tac", fallback: "teek tahk" },
                { country: "Russia", flag: "🇷🇺", sound: "Тик-так", pron: "teek-tahk", native: "тик так", fallback: "teek tahk" },
                { country: "Thailand", flag: "🇹🇭", sound: "ติ๊กต่อก", pron: "teek-toahk", native: "ติ๊กต่อก", fallback: "teek toahk" },
                { country: "Egypt", flag: "🇪🇬", sound: "تيك تاك", pron: "teek-tahk", native: "تيك تاك", fallback: "teek tahk" },
                { country: "Brazil", flag: "🇧🇷", sound: "Tic tac", pron: "teek-tahk", native: "tic tac", fallback: "teek tahk" },
                { country: "China", flag: "🇨🇳", sound: "滴答", pron: "dee-dah", native: "滴答", fallback: "dee dah" },
                { country: "India", flag: "🇮🇳", sound: "टिक-टिक", pron: "teek-teek", native: "टिक टिक", fallback: "teek teek" },
                { country: "Kenya", flag: "🇰🇪", sound: "Tick tock", pron: "tick-tock", native: "tick tock", fallback: "tick tock" },
                { country: "Greece", flag: "🇬🇷", sound: "Τικ τακ", pron: "teek-tahk", native: "τικ τακ", fallback: "tick-tock" }
            ]},
            phone: { id: 'phone', icon: "☎️", name: "Telephone", params: { pitch: 1.1, rate: 1.2 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Ring ring", pron: "ring-ring", native: "ring ring", fallback: "ring ring" },
                { country: "Korea", flag: "🇰🇷", sound: "따르릉", pron: "ttah-reu-reung", native: "따르릉", fallback: "ttah reu reung" },
                { country: "Japan", flag: "🇯🇵", sound: "リンリン", pron: "reen-reen", native: "リンリン", fallback: "reen reen" },
                { country: "Spain", flag: "🇪🇸", sound: "Rin rin", pron: "reen-reen", native: "rin rin", fallback: "reen reen" },
                { country: "France", flag: "🇫🇷", sound: "Drin drin", pron: "dreen-dreen", native: "drin drin", fallback: "dreen dreen" },
                { country: "Germany", flag: "🇩🇪", sound: "Klingeling", pron: "kling-eling", native: "klingeling", fallback: "kling eling" },
                { country: "Italy", flag: "🇮🇹", sound: "Drin drin", pron: "dreen-dreen", native: "drin drin", fallback: "dreen dreen" },
                { country: "Russia", flag: "🇷🇺", sound: "Дзынь-дзынь", pron: "dzeen-dzeen", native: "дзынь дзынь", fallback: "dzeen dzeen" },
                { country: "Thailand", flag: "🇹🇭", sound: "กริ๊งกริ๊ง", pron: "greeng-greeng", native: "กริ๊งกริ๊ง", fallback: "greeng greeng" },
                { country: "Egypt", flag: "🇪🇬", sound: "ترن ترن", pron: "reen-reen", native: "ترن ترن", fallback: "reen reen" },
                { country: "Brazil", flag: "🇧🇷", sound: "Trim trim", pron: "treem-treem", native: "trim trim", fallback: "treem treem" },
                { country: "China", flag: "🇨🇳", sound: "叮铃铃", pron: "deeng-leeng", native: "叮铃铃", fallback: "deeng leeng" },
                { country: "India", flag: "🇮🇳", sound: "ट्रिंग-ट्रिंग", pron: "treeng-treeng", native: "ट्रिंग ट्रिंग", fallback: "treeng treeng" },
                { country: "Kenya", flag: "🇰🇪", sound: "Ring ring", pron: "ring-ring", native: "ring ring", fallback: "ring ring" },
                { country: "Greece", flag: "🇬🇷", sound: "Ντριν ντριν", pron: "dreen-dreen", native: "ντριν ντριν", fallback: "dreen-dreen" }
            ]},
            bell: { id: 'bell', icon: "🔔", name: "Doorbell", params: { pitch: 1.3, rate: 0.9 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Ding dong", pron: "deeng-doahng", native: "ding dong", fallback: "deeng doahng" },
                { country: "Korea", flag: "🇰🇷", sound: "딩동", pron: "deeng-doahng", native: "딩동", fallback: "deeng doahng" },
                { country: "Japan", flag: "🇯🇵", sound: "핀포온", pron: "peen-poah-n", native: "ピンポーン", fallback: "peen poahn" },
                { country: "Spain", flag: "🇪🇸", sound: "Din don", pron: "deen-doahn", native: "din don", fallback: "deen doahn" },
                { country: "France", flag: "🇫🇷", sound: "Ding dong", pron: "deeng-doahng", native: "ding dong", fallback: "deeng doahng" },
                { country: "Germany", flag: "🇩🇪", sound: "Ding dong", pron: "deeng-doahng", native: "ding dong", fallback: "deeng doahng" },
                { country: "Italy", flag: "🇮🇹", sound: "Din don", pron: "deen-doahn", native: "din don", fallback: "deen doahn" },
                { country: "Russia", flag: "🇷🇺", sound: "Дзинь-дон", pron: "dzeen-doahn", native: "дзынь дон", fallback: "dzeen doahn" },
                { country: "Thailand", flag: "🇹🇭", sound: "ติ๊งต่อง", pron: "teeng-toahng", native: "ติ๊งต่อง", fallback: "teeng toahng" },
                { country: "Egypt", flag: "🇪🇬", sound: "دينغ دونغ", pron: "deeng-doahng", native: "دينغ دونغ", fallback: "deeng doahng" },
                { country: "Brazil", flag: "🇧🇷", sound: "Dim dom", pron: "deem-doahn", native: "dim dom", fallback: "deem doahn" },
                { country: "China", flag: "🇨🇳", sound: "叮咚", pron: "deeng-doahng", native: "叮咚", fallback: "deeng doahng" },
                { country: "India", flag: "🇮🇳", sound: "डिंग डोंग", pron: "deeng-doahng", native: "डिंग डोंग", fallback: "deeng doahng" },
                { country: "Kenya", flag: "🇰🇪", sound: "Ding dong", pron: "deeng-doahng", native: "ding dong", fallback: "deeng doahng" },
                { country: "Greece", flag: "🇬🇷", sound: "Ντινγκ ντονγκ", pron: "deeng-doahng", native: "ντινγκ ντονγκ", fallback: "ding-dong" }
            ]},
            explosion: { id: 'explosion', icon: "💥", name: "Explosion", params: { pitch: 0.5, rate: 0.7 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Boom", pron: "boooahm", native: "boom", fallback: "boooahm" },
                { country: "Korea", flag: "🇰🇷", sound: "쾅", pron: "kwahng", native: "쾅", fallback: "kwahng" },
                { country: "Japan", flag: "🇯🇵", sound: "ドカーン", pron: "doah-kah-an", native: "ドカーン", fallback: "doah kah an" },
                { country: "Spain", flag: "🇪🇸", sound: "¡Bum!", pron: "boooahm", native: "bum", fallback: "boooahm" },
                { country: "France", flag: "🇫🇷", sound: "Boum", pron: "boooahm", native: "boum", fallback: "boooahm" },
                { country: "Germany", flag: "🇩🇪", sound: "Bumm", pron: "boooahm", native: "bumm", fallback: "boooahm" },
                { country: "Italy", flag: "🇮🇹", sound: "Bum", pron: "boooahm", native: "bum", fallback: "boooahm" },
                { country: "Russia", flag: "🇷🇺", sound: "Бабах", pron: "bah-bahkh", native: "бабах", fallback: "bah bahkh" },
                { country: "Thailand", flag: "🇹🇭", sound: "ตู้ม", pron: "toooahm", native: "ตู้ม", fallback: "toooahm" },
                { country: "Egypt", flag: "🇪🇬", sound: "بووم", pron: "boooahm", native: "بووم", fallback: "boooahm" },
                { country: "Brazil", flag: "🇧🇷", sound: "Cabrum", pron: "kah-boooahm", native: "cabrum", fallback: "kah boooahm" },
                { country: "China", flag: "🇨🇳", sound: "轰", pron: "hoahng", native: "轰", fallback: "hoahng" },
                { country: "India", flag: "🇮🇳", sound: "धमाका", pron: "dhah-mah-kah", native: "धमाका", fallback: "dhah mah kah" },
                { country: "Kenya", flag: "🇰🇪", sound: "Boom", pron: "boooahm", native: "boom", fallback: "boooahm" },
                { country: "Greece", flag: "🇬🇷", sound: "Μπαμ", pron: "bahm", native: "μπαμ", fallback: "bahm" }
            ]},
            pop: { id: 'pop', icon: "🎈", name: "Pop", params: { pitch: 1.2, rate: 1.1 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Pop", pron: "poahp", native: "pop", fallback: "poahp" },
                { country: "Korea", flag: "🇰🇷", sound: "뻥", pron: "ppuhng", native: "뻥", fallback: "ppuhng" },
                { country: "Japan", flag: "🇯🇵", sound: "パチン", pron: "pah-cheen", native: "パチン", fallback: "pah cheen" },
                { country: "Spain", flag: "🇪🇸", sound: "Pum", pron: "poooahm", native: "pum", fallback: "poooahm" },
                { country: "France", flag: "🇫🇷", sound: "Pan", pron: "pah-n", native: "pan", fallback: "pahn" },
                { country: "Germany", flag: "🇩🇪", sound: "Paff", pron: "pah-f", native: "paff", fallback: "pahf" },
                { country: "Italy", flag: "🇮🇹", sound: "Pof", pron: "poah-f", native: "pof", fallback: "poahf" },
                { country: "Russia", flag: "🇷🇺", sound: "Хлоп", pron: "khloahp", native: "хлоп", fallback: "khloahp" },
                { country: "Thailand", flag: "🇹🇭", sound: "ปัง", pron: "pahng", native: "ปัง", fallback: "pahng" },
                { country: "Egypt", flag: "🇪🇬", sound: "بوپ", pron: "poahp", native: "بوپ", fallback: "poahp" },
                { country: "Brazil", flag: "🇧🇷", sound: "Ploc", pron: "ploahk", native: "ploc", fallback: "ploahk" },
                { country: "China", flag: "🇨🇳", sound: "啪", pron: "pah", native: "啪", fallback: "pah" },
                { country: "India", flag: "🇮🇳", sound: "पटाक", pron: "pah-tahk", native: "पटाक", fallback: "pah tahk" },
                { country: "Kenya", flag: "🇰🇪", sound: "Pop", pron: "poahp", native: "pop", fallback: "poahp" },
                { country: "Greece", flag: "🇬🇷", sound: "Ποπ", pron: "poahp", native: "ποπ", fallback: "pop" }
            ]},
            glass: { id: 'glass', icon: "🥂", name: "Glass Break", params: { pitch: 1.4, rate: 1.2 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Crash", pron: "krahsh", native: "crash", fallback: "krahsh" },
                { country: "Korea", flag: "🇰🇷", sound: "와장창", pron: "wah-jahng", native: "와장창", fallback: "wah jahng" },
                { country: "Japan", flag: "🇯🇵", sound: "ガシャン", pron: "gah-shahn", native: "ガシャン", fallback: "gah shahn" },
                { country: "Spain", flag: "🇪🇸", sound: "Catapum", pron: "kah-tah-pooahm", native: "catapum", fallback: "kah tah pooahm" },
                { country: "France", flag: "🇫🇷", sound: "Crac", pron: "krahck", native: "crac", fallback: "krahck" },
                { country: "Germany", flag: "🇩🇪", sound: "Klirr", pron: "kleer", native: "klirr", fallback: "kleer" },
                { country: "Italy", flag: "🇮🇹", sound: "Fracass", pron: "frah-kahss", native: "fracass", fallback: "frah kahss" },
                { country: "Russia", flag: "🇷🇺", sound: "Дзынь", pron: "dzeen", native: "дзынь", fallback: "dzeen" },
                { country: "Thailand", flag: "🇹🇭", sound: "เพล้ง", pron: "playng", native: "เพล้ง", fallback: "playng" },
                { country: "Egypt", flag: "🇪🇬", sound: "طخ", pron: "tahkh", native: "طخ", fallback: "tahkh" },
                { country: "Brazil", flag: "🇧🇷", sound: "Cras", pron: "krahsh", native: "cras", fallback: "krahsh" },
                { country: "China", flag: "🇨🇳", sound: "哐啷", pron: "kwahng-lahng", native: "哐啷", fallback: "kwahng lahng" },
                { country: "India", flag: "🇮🇳", sound: "छन", pron: "chhahn", native: "छन", fallback: "chhahn" },
                { country: "Kenya", flag: "🇰🇪", sound: "Crash", pron: "krahsh", native: "crash", fallback: "krahsh" },
                { country: "Greece", flag: "🇬🇷", sound: "Κρακ", pron: "krahck", native: "κρακ", fallback: "krah-ck" }
            ]},
            drip: { id: 'drip', icon: "💧", name: "Water Drop", params: { pitch: 1.2, rate: 1.2 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Drip", pron: "dreep", native: "drip", fallback: "dreep" },
                { country: "Korea", flag: "🇰🇷", sound: "똑똑", pron: "ttok-ttok", native: "똑똑", fallback: "ttok ttok" },
                { country: "Japan", flag: "🇯🇵", sound: "ポツン", pron: "po-tsoon", native: "ポツン", fallback: "po tsoon" },
                { country: "Spain", flag: "🇪🇸", sound: "Ploc", pron: "ploahk", native: "ploc", fallback: "ploahk" },
                { country: "France", flag: "🇫🇷", sound: "Plic", pron: "pleeck", native: "plic", fallback: "pleeck" },
                { country: "Germany", flag: "🇩🇪", sound: "Plitsch", pron: "pleetsh", native: "plitsch", fallback: "pleetsh" },
                { country: "Italy", flag: "🇮🇹", sound: "Ploc", pron: "ploahk", native: "ploc", fallback: "ploahk" },
                { country: "Russia", flag: "🇷🇺", sound: "Кап-кап", pron: "kahp-kahp", native: "кап кап", fallback: "kahp kahp" },
                { country: "Thailand", flag: "🇹🇭", sound: "ติ๋ง", pron: "teeng", native: "ติ๋ง", fallback: "teeng" },
                { country: "Egypt", flag: "🇪🇬", sound: "نقطة", pron: "noak-tah", native: "نقطة", fallback: "noak tah" },
                { country: "Brazil", flag: "🇧🇷", sound: "Ping", pron: "peeng", native: "ping", fallback: "peeng" },
                { country: "China", flag: "🇨🇳", sound: "滴", pron: "deee", native: "滴", fallback: "deee" },
                { country: "India", flag: "🇮🇳", sound: "टपक", pron: "tah-pahk", native: "टपक", fallback: "tah pahk" },
                { country: "Kenya", flag: "🇰🇪", sound: "Drip", pron: "dreep", native: "drip", fallback: "dreep" },
                { country: "Greece", flag: "🇬🇷", sound: "Πλιτς", pron: "pleets", native: "πλιτς", fallback: "plits" }
            ]},
            zipper: { id: 'zipper', icon: "🤐", name: "Zipper", params: { pitch: 1.1, rate: 1.5 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Zip", pron: "zeeehp", native: "zip", fallback: "zip" },
                { country: "Korea", flag: "🇰🇷", sound: "지익", pron: "jee-eek", native: "지익", fallback: "jee eek" },
                { country: "Japan", flag: "🇯🇵", sound: "ジー", pron: "jeee", native: "ジー", fallback: "jeee" },
                { country: "Spain", flag: "🇪🇸", sound: "Zip", pron: "zeeehp", native: "zip", fallback: "zip" },
                { country: "France", flag: "🇫🇷", sound: "Zipp", pron: "zeeehp", native: "zipp", fallback: "zipp" },
                { country: "Germany", flag: "🇩🇪", sound: "Ritsch", pron: "reetsh", native: "ritsch", fallback: "reetsh" },
                { country: "Italy", flag: "🇮🇹", sound: "Zip", pron: "zeeehp", native: "zip", fallback: "zip" },
                { country: "Russia", flag: "🇷🇺", sound: "Вж-ж", pron: "vzhzh", native: "вж ж", fallback: "vzhzh" },
                { country: "Thailand", flag: "🇹🇭", sound: "รู드", pron: "rooat", native: "รูด", fallback: "rooat" },
                { country: "Egypt", flag: "🇪🇬", sound: "سحاب", pron: "sah-hahb", native: "سحاب", fallback: "sah hahb" },
                { country: "Brazil", flag: "🇧🇷", sound: "Zupt", pron: "zooahmpt", native: "zupt", fallback: "zupt" },
                { country: "China", flag: "🇨🇳", sound: "哧", pron: "cheee", native: "哧", fallback: "cheee" },
                { country: "India", flag: "🇮🇳", sound: "ज़िप", pron: "zeeehp", native: "ज़िप", fallback: "zip" },
                { country: "Kenya", flag: "🇰🇪", sound: "Zip", pron: "zeeehp", native: "zip", fallback: "zip" },
                { country: "Greece", flag: "🇬🇷", sound: "Ζιπ", pron: "zeeehp", native: "ζιπ", fallback: "zip" }
            ]},
            click: { id: 'click', icon: "🖱️", name: "Click", params: { pitch: 1.1, rate: 1.2 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Click", pron: "cleeck", native: "click", fallback: "cleeck" },
                { country: "Korea", flag: "🇰🇷", sound: "딸깍", pron: "ttal-kkahk", native: "딸깍", fallback: "ttal kkahk" },
                { country: "Japan", flag: "🇯🇵", sound: "カチッ", pron: "kah-chee", native: "カチッ", fallback: "kah chee" },
                { country: "Spain", flag: "🇪🇸", sound: "Clic", pron: "cleeck", native: "clic", fallback: "cleeck" },
                { country: "France", flag: "🇫🇷", sound: "Clic", pron: "cleeck", native: "clic", fallback: "cleeck" },
                { country: "Germany", flag: "🇩🇪", sound: "Klick", pron: "cleeck", native: "klick", fallback: "cleeck" },
                { country: "Italy", flag: "🇮🇹", sound: "Clic", pron: "cleeck", native: "clic", fallback: "cleeck" },
                { country: "Russia", flag: "🇷🇺", sound: "Клик", pron: "cleeck", native: "клик", fallback: "cleeck" },
                { country: "Thailand", flag: "🇹🇭", sound: "คลิก", pron: "cleeck", native: "คลิก", fallback: "cleeck" },
                { country: "Egypt", flag: "🇪🇬", sound: "كليك", pron: "cleeck", native: "كليك", fallback: "cleeck" },
                { country: "Brazil", flag: "🇧🇷", sound: "Clique", pron: "clee-kee", native: "clique", fallback: "cleekee" },
                { country: "China", flag: "🇨🇳", sound: "咔", pron: "kaah", native: "咔", fallback: "kaah" },
                { country: "India", flag: "🇮🇳", sound: "क्लिक", pron: "cleeck", native: "क्लिक", fallback: "cleeck" },
                { country: "Kenya", flag: "🇰🇪", sound: "Click", pron: "cleeck", native: "click", fallback: "cleeck" },
                { country: "Greece", flag: "🇬🇷", sound: "Κλικ", pron: "cleeck", native: "κλικ", fallback: "clik" }
            ]},
            camera: { id: 'camera', icon: "📸", name: "Camera", params: { pitch: 1.1, rate: 1.2 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Click", pron: "cleeck", native: "click", fallback: "cleeck" },
                { country: "Korea", flag: "🇰🇷", sound: "찰칵", pron: "chal-kahk", native: "찰칵", fallback: "chal kahk" },
                { country: "Japan", flag: "🇯🇵", sound: "카샤", pron: "kah-shah", native: "カシャ", fallback: "kah shah" },
                { country: "Spain", flag: "🇪🇸", sound: "Clic", pron: "cleeck", native: "clic", fallback: "cleeck" },
                { country: "France", flag: "🇫🇷", sound: "Clic", pron: "cleeck", native: "clic", fallback: "cleeck" },
                { country: "Germany", flag: "🇩🇪", sound: "Knips", pron: "kneeps", native: "knips", fallback: "kneeps" },
                { country: "Italy", flag: "🇮🇹", sound: "Clic", pron: "cleeck", native: "clic", fallback: "cleeck" },
                { country: "Russia", flag: "🇷🇺", sound: "Щёлк", pron: "shchyolk", native: "щёлк", fallback: "shchyolk" },
                { country: "Thailand", flag: "🇹🇭", sound: "แชะ", pron: "chae", native: "แชะ", fallback: "chae" },
                { country: "Egypt", flag: "🇪🇬", sound: "كليك", pron: "cleeck", native: "كليك", fallback: "cleeck" },
                { country: "Brazil", flag: "🇧🇷", sound: "Click", pron: "cleeck", native: "click", fallback: "cleeck" },
                { country: "China", flag: "🇨🇳", sound: "咔嚓", pron: "kah-chah", native: "咔嚓", fallback: "kah chah" },
                { country: "India", flag: "🇮🇳", sound: "क्लिक", pron: "cleeck", native: "क्लिक", fallback: "cleeck" },
                { country: "Kenya", flag: "🇰🇪", sound: "Click", pron: "cleeck", native: "click", fallback: "cleeck" },
                { country: "Greece", flag: "🇬🇷", sound: "Κλικ", pron: "cleeck", native: "κλικ", fallback: "click" }
            ]},
            spark: { id: 'spark', icon: "⚡", name: "Spark", params: { pitch: 1.3, rate: 1.1 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Zap", pron: "zahmp", native: "zap", fallback: "zap" },
                { country: "Korea", flag: "🇰🇷", sound: "지지직", pron: "jee-jee", native: "지지직", fallback: "jee jee" },
                { country: "Japan", flag: "🇯🇵", sound: "ビリビリ", pron: "bee-ree", native: "ビリビリ", fallback: "bee ree" },
                { country: "Spain", flag: "🇪🇸", sound: "Zap", pron: "zahmp", native: "zap", fallback: "zap" },
                { country: "France", flag: "🇫🇷", sound: "Zzz", pron: "zzzzzz", native: "zzz", fallback: "zzzz" },
                { country: "Germany", flag: "🇩🇪", sound: "Zzzt", pron: "zzzzzz", native: "zzzt", fallback: "zzzt" },
                { country: "Italy", flag: "🇮🇹", sound: "Zzz", pron: "zzzzzz", native: "zzz", fallback: "zzzz" },
                { country: "Russia", flag: "🇷🇺", sound: "Бз-з", pron: "bzzzzz", native: "бзз", fallback: "bzz" },
                { country: "Thailand", flag: "🇹🇭", sound: "เปรี๊ยะ", pron: "pree-ah", native: "เปรี๊ยะ", fallback: "pree ah" },
                { country: "Egypt", flag: "🇪🇬", sound: "طنين", pron: "zah-neen", native: "طنين", fallback: "zah neen" },
                { country: "Brazil", flag: "🇧🇷", sound: "Bzz", pron: "bzzzzz", native: "bzz", fallback: "bzzz" },
                { country: "China", flag: "🇨🇳", sound: "滋", pron: "zeee", native: "滋", fallback: "zeee" },
                { country: "India", flag: "🇮🇳", sound: "झटका", pron: "jhah-tah", native: "झटका", fallback: "jhah tah" },
                { country: "Kenya", flag: "🇰🇪", sound: "Zap", pron: "zahmp", native: "zap", fallback: "zap" },
                { country: "Greece", flag: "🇬🇷", sound: "Ζαπ", pron: "zahmp", native: "ζαπ", fallback: "zap" }
            ]},
            boiling: { id: 'boiling', icon: "🍲", name: "Boiling", params: { pitch: 1.1, rate: 1.2 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Bubble", pron: "buh-buhl", native: "bubble", fallback: "buh buhl" },
                { country: "Korea", flag: "🇰🇷", sound: "보글보글", pron: "bo-geul", native: "보글보글", fallback: "bo geul" },
                { country: "Japan", flag: "🇯🇵", sound: "プクプク", pron: "poo-koo", native: "プクプク", fallback: "poo koo" },
                { country: "Spain", flag: "🇪🇸", sound: "Glogló", pron: "glo-gloah", native: "glogló", fallback: "glo gloah" },
                { country: "France", flag: "🇫🇷", sound: "Glou glou", pron: "gloo-gloo", native: "glou glou", fallback: "gloo gloo" },
                { country: "Germany", flag: "🇩🇪", sound: "Blub", pron: "blooahb", native: "blub", fallback: "blooahb" },
                { country: "Italy", flag: "🇮🇹", sound: "Boll", pron: "boahll", native: "boll", fallback: "boahll" },
                { country: "Russia", flag: "🇷🇺", sound: "Буль-буль", pron: "bool-bool", native: "буль буль", fallback: "bool bool" },
                { country: "Thailand", flag: "🇹🇭", sound: "ปุดปุด", pron: "poot-poot", native: "ปุดปุด", fallback: "poot poot" },
                { country: "Egypt", flag: "🇪🇬", sound: "غلية", pron: "ghah-lyah", native: "غلية", fallback: "ghah lyah" },
                { country: "Brazil", flag: "🇧🇷", sound: "Bolha", pron: "boahl-hah", native: "bolha", fallback: "boahl hah" },
                { country: "China", flag: "🇨🇳", sound: "咕嘟", pron: "goo-doo", native: "咕嘟", fallback: "goo doo" },
                { country: "India", flag: "🇮🇳", sound: "बुलबुल", pron: "bool-bool", native: "बुलबुल", fallback: "bool bool" },
                { country: "Kenya", flag: "🇰🇪", sound: "Bubble", pron: "buh-buhl", native: "bubble", fallback: "buh buhl" },
                { country: "Greece", flag: "🇬🇷", sound: "Μπουρμπουλήθρα", pron: "boor-boo", native: "μπουρμπουλήθρα", fallback: "bur-bu" }
            ]},
            frying: { id: 'frying', icon: "🍳", name: "Frying", params: { pitch: 1.0, rate: 1.4 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Sizzle", pron: "see-zuhl", native: "sizzle", fallback: "see zuhl" },
                { country: "Korea", flag: "🇰🇷", sound: "지글지글", pron: "jee-geul", native: "지글지글", fallback: "jee geul" },
                { country: "Japan", flag: "🇯🇵", sound: "ジュージュー", pron: "jyuu-jyuu", native: "ジュージュー", fallback: "jyuu jyuu" },
                { country: "Spain", flag: "🇪🇸", sound: "Pshhh", pron: "pshhhhh", native: "pshhh", fallback: "pshhhh" },
                { country: "France", flag: "🇫🇷", sound: "Pshhh", pron: "pshhhhh", native: "pshhh", fallback: "pshhhh" },
                { country: "Germany", flag: "🇩🇪", sound: "Zisch", pron: "zeeesh", native: "zisch", fallback: "zeeesh" },
                { country: "Italy", flag: "🇮🇹", sound: "Frigg", pron: "free-jj", native: "frigg", fallback: "free jj" },
                { country: "Russia", flag: "🇷🇺", sound: "Шипение", pron: "shee-peh", native: "шипение", fallback: "shee peh" },
                { country: "Thailand", flag: "🇹🇭", sound: "ฉ่า", pron: "chah", native: "ฉ่า", fallback: "chah" },
                { country: "Egypt", flag: "🇪🇬", sound: "قلي", pron: "kah-lee", native: "قلي", fallback: "kah lee" },
                { country: "Brazil", flag: "🇧🇷", sound: "Chiado", pron: "shee-ah-do", native: "chiado", fallback: "shee ah do" },
                { country: "China", flag: "🇨🇳", sound: "滋滋", pron: "zeee-zeee", native: "滋滋", fallback: "zeee zeee" },
                { country: "India", flag: "🇮🇳", sound: "छन-छन", pron: "chhahn", native: "छन छन", fallback: "chhahn" },
                { country: "Kenya", flag: "🇰🇪", sound: "Sizzle", pron: "see-zuhl", native: "sizzle", fallback: "see zuhl" },
                { country: "Greece", flag: "🇬🇷", sound: "Τσιτσίρισμα", pron: "tsee-tsee", native: "τσιτσίρισμα", fallback: "tsi-tsi" }
            ]}
        }
    },
    humans: {
        title: "Humans", icon: "👤", subtitle: "Do we all make the same sounds? 💓",
        data: {
            heart: { id: 'heart', icon: "💓", name: "Heartbeat", params: { pitch: 0.7, rate: 0.8 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Thump thump", pron: "thahmp", native: "thump thump", fallback: "thahmp thahmp" },
                { country: "Korea", flag: "🇰🇷", sound: "두근두근", pron: "doo-geun", native: "두근두근", fallback: "doo geun" },
                { country: "Japan", flag: "🇯🇵", sound: "ドキドキ", pron: "do-kee", native: "ドキドキ", fallback: "do kee" },
                { country: "Spain", flag: "🇪🇸", sound: "Bum bum", pron: "boooahm", native: "bum bum", fallback: "boooahm" },
                { country: "France", flag: "🇫🇷", sound: "Boum boum", pron: "boooahm", native: "boum boum", fallback: "boooahm" },
                { country: "Germany", flag: "🇩🇪", sound: "Pock pock", pron: "poahck", native: "pock pock", fallback: "poahck" },
                { country: "Italy", flag: "🇮🇹", sound: "Tu tum", pron: "too-tooom", native: "tu tum", fallback: "too toom" },
                { country: "Russia", flag: "🇷🇺", sound: "Тук-тук", pron: "took-took", native: "тук тук", fallback: "took took" },
                { country: "Thailand", flag: "🇹🇭", sound: "ตุ๊บตุ๊บ", pron: "toop-toop", native: "ตุ๊บตุ๊บ", fallback: "toop toop" },
                { country: "Egypt", flag: "🇪🇬", sound: "دق دق", pron: "dahk-dahk", native: "دق دق", fallback: "dahk dahk" },
                { country: "Brazil", flag: "🇧🇷", sound: "Tum tum", pron: "tooom", native: "tum tum", fallback: "tooom" },
                { country: "China", flag: "🇨🇳", sound: "噗通", pron: "poo-toahng", native: "噗通", fallback: "poo toahng" },
                { country: "India", flag: "🇮🇳", sound: "धक्-धक्", pron: "dhahk", native: "धक् धक्", fallback: "dhahk" },
                { country: "Kenya", flag: "🇰🇪", sound: "Dunda dunda", pron: "doon-dah", native: "dunda dunda", fallback: "doon dah" },
                { country: "Greece", flag: "🇬🇷", sound: "Ντουκ ντουκ", pron: "dooak", native: "ντουκ ντουκ", fallback: "duk-duk" }
            ]},
            shiver: { id: 'shiver', icon: "🥶", name: "Shivering", params: { pitch: 1.5, rate: 1.5 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Brrr", pron: "brrrrr", native: "brrr", fallback: "brrr" },
                { country: "Korea", flag: "🇰🇷", sound: "덜덜", pron: "duhl-duhl", native: "덜덜", fallback: "duhl duhl" },
                { country: "Japan", flag: "🇯🇵", sound: "ブルブル", pron: "boo-roo", native: "ブルブル", fallback: "boo roo" },
                { country: "Spain", flag: "🇪🇸", sound: "Qué frío", pron: "free-oah", native: "qué frío", fallback: "free oah" },
                { country: "France", flag: "🇫🇷", sound: "Gla gla", pron: "glah-glah", native: "gla gla", fallback: "glah glah" },
                { country: "Germany", flag: "🇩🇪", sound: "Zitter", pron: "tseet-ter", native: "zitter", fallback: "tseet ter" },
                { country: "Italy", flag: "🇮🇹", sound: "Brrr", pron: "brrrrr", native: "brrr", fallback: "brrr" },
                { country: "Russia", flag: "🇷🇺", sound: "Бр-р", pron: "brrrrr", native: "бр р", fallback: "brrr" },
                { country: "Thailand", flag: "🇹🇭", sound: "บรื๋อ", pron: "brrrrr", native: "บรื๋อ", fallback: "brrr" },
                { country: "Egypt", flag: "🇪🇬", sound: "برد", pron: "bah-rd", native: "برد", fallback: "bah rd" },
                { country: "Brazil", flag: "🇧🇷", sound: "Gelado", pron: "jeh-lah-do", native: "gelado", fallback: "jeh lah do" },
                { country: "China", flag: "🇨🇳", sound: "瑟瑟", pron: "seh-seh", native: "瑟瑟", fallback: "seh seh" },
                { country: "India", flag: "🇮🇳", sound: "थर-थर", pron: "thahr", native: "थर थर", fallback: "thahr" },
                { country: "Kenya", flag: "🇰🇪", sound: "Tetemeka", pron: "teh-teh", native: "tetemeka", fallback: "teh teh" },
                { country: "Greece", flag: "🇬🇷", sound: "Τρέμουλο", pron: "treh-moo", native: "τρέμουλο", fallback: "tremulo" }
            ]},
            sniff: { id: 'sniff', icon: "😢", name: "Sniffling", params: { pitch: 1.2, rate: 1.1 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Sniff", pron: "sneef", native: "sniff", fallback: "sneef" },
                { country: "Korea", flag: "🇰🇷", sound: "훌쩍훌쩍", pron: "hool-jjeok", native: "훌쩍훌쩍", fallback: "hool jjeok" },
                { country: "Japan", flag: "🇯🇵", sound: "グスン", pron: "goo-soon", native: "グスン", fallback: "goo soon" },
                { country: "Spain", flag: "🇪🇸", sound: "Snif", pron: "sneef", native: "snif", fallback: "sneef" },
                { country: "France", flag: "🇫🇷", sound: "Renifler", pron: "reh-nee", native: "renifler", fallback: "reh nee" },
                { country: "Germany", flag: "🇩🇪", sound: "Schnief", pron: "shneef", native: "schnief", fallback: "shneef" },
                { country: "Italy", flag: "🇮🇹", sound: "Sniff", pron: "sneef", native: "sniff", fallback: "sneef" },
                { country: "Russia", flag: "🇷🇺", sound: "Шмыг", pron: "shmyeg", native: "шмыг", fallback: "shmyeg" },
                { country: "Thailand", flag: "🇹🇭", sound: "ฟืดฟาด", pron: "foo-at", native: "ฟืดฟาด", fallback: "foo at" },
                { country: "Egypt", flag: "🇪🇬", sound: "شهيق", pron: "shah-heeq", native: "شهيق", fallback: "shah heeq" },
                { country: "Brazil", flag: "🇧🇷", sound: "Snif", pron: "sneef", native: "snif", fallback: "sneef" },
                { country: "China", flag: "🇨🇳", sound: "抽泣", pron: "choah", native: "抽泣", fallback: "choah" },
                { country: "India", flag: "🇮🇳", sound: "सुबक나", pron: "soo-bahk", native: "सुबकना", fallback: "soo bahk" },
                { country: "Kenya", flag: "🇰🇪", sound: "Sniff", pron: "sneef", native: "sniff", fallback: "sneef" },
                { country: "Greece", flag: "🇬🇷", sound: "Ρουθούνισμα", pron: "roo-thee", native: "ρουθούνισμα", fallback: "snif" }
            ]},
            laugh: { id: 'laugh', icon: "😂", name: "Laughing", params: { pitch: 1.1, rate: 1.1 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Haha", pron: "hah-hah", native: "hah hah hah", fallback: "hah hah hah" },
                { country: "Korea", flag: "🇰🇷", sound: "하하", pron: "hah-hah", native: "하하 하", fallback: "hah hah hah" },
                { country: "Japan", flag: "🇯🇵", sound: "ワハハ", pron: "wa-ha-ha", native: "ワハハ", fallback: "wah hah hah" },
                { country: "Spain", flag: "🇪🇸", sound: "Jaja", pron: "hah-hah", native: "hah hah hah", fallback: "hah hah hah" },
                { country: "France", flag: "🇫🇷", sound: "Haha", pron: "hah-hah", native: "hah hah", fallback: "hah hah" },
                { country: "Germany", flag: "🇩🇪", sound: "Haha", pron: "hah-hah", native: "hah hah", fallback: "hah hah" },
                { country: "Italy", flag: "🇮🇹", sound: "Ah ah", pron: "ah-ah", native: "ah ah", fallback: "ah ah" },
                { country: "Russia", flag: "🇷🇺", sound: "Ха-ха", pron: "hah-hah", native: "ха ха ха", fallback: "hah hah hah" },
                { country: "Thailand", flag: "🇹🇭", sound: "555", pron: "ha-ha-ha", native: "ห้า ห้า ห้า", fallback: "hah hah hah" },
                { country: "Egypt", flag: "🇪🇬", sound: "هههه", pron: "hahahahaha", native: "هههه", fallback: "hahahahaha" },
                { country: "Brazil", flag: "🇧🇷", sound: "Kkkk", pron: "kah-kah-kah", native: "kkkk", fallback: "kah kah kah kah" },
                { country: "China", flag: "🇨🇳", sound: "哈哈", pron: "hah-hah", native: "哈哈", fallback: "hah hah" },
                { country: "India", flag: "🇮🇳", sound: "हा-हा", pron: "hah-hah", native: "हा 하", fallback: "hah hah" },
                { country: "Kenya", flag: "🇰🇪", sound: "Haha", pron: "hah-hah", native: "hah hah", fallback: "hah hah" },
                { country: "Greece", flag: "🇬🇷", sound: "Χαχα", pron: "hah-hah", native: "χα χα", fallback: "haha" }
            ]},
            cry: { id: 'cry', icon: "😭", name: "Crying", params: { pitch: 1.0, rate: 0.9 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Wahhh", pron: "wah-ah-ah", native: "wahhh", fallback: "wahhh" },
                { country: "Korea", flag: "🇰🇷", sound: "엉엉", pron: "uhng-uhng", native: "엉엉", fallback: "uhng uhng" },
                { country: "Japan", flag: "🇯🇵", sound: "エーンエーン", pron: "aehn-aehn", native: "エーンエーン", fallback: "aehn aehn" },
                { country: "Spain", flag: "🇪🇸", sound: "Buaaa", pron: "bwah-ah-ah", native: "buaaa", fallback: "buaaa" },
                { country: "France", flag: "🇫🇷", sound: "Ouin ouin", pron: "wah-n", native: "ouin ouin", fallback: "ouin ouin" },
                { country: "Germany", flag: "🇩🇪", sound: "Buhu", pron: "booo-hoo", native: "buhu", fallback: "buhu" },
                { country: "Italy", flag: "🇮🇹", sound: "Ueue", pron: "way-way", native: "ueue", fallback: "ueue" },
                { country: "Russia", flag: "🇷🇺", sound: "Ы-ы-ы", pron: "ee-ee-ee", native: "ы ы ы", fallback: "ee ee ee" },
                { country: "Thailand", flag: "🇹🇭", sound: "แงแง", pron: "ngae-ngae", native: "แงแง", fallback: "ngae ngae" },
                { country: "Egypt", flag: "🇪🇬", sound: "بكاء", pron: "boo-kah", native: "بكاء", fallback: "boo kah" },
                { country: "Brazil", flag: "🇧🇷", sound: "Buá", pron: "bwah", native: "buá", fallback: "buá" },
                { country: "China", flag: "🇨🇳", sound: "呜呜", pron: "woo-woo", native: "呜呜", fallback: "呜呜" },
                { country: "India", flag: "🇮🇳", sound: "ऊ-ऊ", pron: "oooo-oooo", native: "ऊ ऊ", fallback: "oo oo" },
                { country: "Kenya", flag: "🇰🇪", sound: "Lia", pron: "lee-ah", native: "lia", fallback: "lee ah" },
                { country: "Greece", flag: "🇬🇷", sound: "Κλάμα", pron: "klah-mah", native: "κλάμα", fallback: "wahhh" }
            ]},
            sneeze: { id: 'sneeze', icon: "🤧", name: "Sneeze", params: { pitch: 1.2, rate: 1.2 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Achoo", pron: "ah-chooo", native: "achoo", fallback: "achoo" },
                { country: "Korea", flag: "🇰🇷", sound: "에취", pron: "eh-chwee", native: "에취", fallback: "eh chwee" },
                { country: "Japan", flag: "🇯🇵", sound: "ハクション", pron: "hah-koo-shon", native: "ハクション", fallback: "hah koo shon" },
                { country: "Spain", flag: "🇪🇸", sound: "Achís", pron: "ah-chees", native: "achís", fallback: "ah chees" },
                { country: "France", flag: "🇫🇷", sound: "Atchoum", pron: "ah-shoo", native: "atchoum", fallback: "ah shoo" },
                { country: "Germany", flag: "🇩🇪", sound: "Hatschi", pron: "hah-chee", native: "hatschi", fallback: "hah chee" },
                { country: "Italy", flag: "🇮🇹", sound: "Etciù", pron: "et-chooo", native: "etciù", fallback: "et chooo" },
                { country: "Russia", flag: "🇷🇺", sound: "Апчхи", pron: "ahp-chee", native: "апчхи", fallback: "ahp chee" },
                { country: "Thailand", flag: "🇹🇭", sound: "ฮัดเช่ย", pron: "haht-chay", native: "ฮัดเช่ย", fallback: "haht chay" },
                { country: "Egypt", flag: "🇪🇬", sound: "اتشو", pron: "at-sho", native: "اتشو", fallback: "at sho" },
                { country: "Brazil", flag: "🇧🇷", sound: "Atchim", pron: "aht-sheem", native: "atchim", fallback: "aht sheem" },
                { country: "China", flag: "🇨🇳", sound: "阿嚏", pron: "ah-tee", native: "阿嚏", fallback: "ah tee" },
                { country: "India", flag: "🇮🇳", sound: "आछीं", pron: "aah-chee", native: "आछीं", fallback: "aah chee" },
                { country: "Kenya", flag: "🇰🇪", sound: "Achoo", pron: "ah-chooo", native: "achoo", fallback: "achoo" },
                { country: "Greece", flag: "🇬🇷", sound: "Αψού", pron: "ahp-soo", native: "αψού", fallback: "achoo" }
            ]},
            cough: { id: 'cough', icon: "😷", name: "Cough", params: { pitch: 0.8, rate: 1.0 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Hack", pron: "hahck", native: "hack", fallback: "hahck" },
                { country: "Korea", flag: "🇰🇷", sound: "콜록콜록", pron: "koahl-loahk", native: "콜록콜록", fallback: "koahl loahk" },
                { country: "Japan", flag: "🇯🇵", sound: "ゴホゴホ", pron: "go-ho", native: "ゴホゴホ", fallback: "go ho" },
                { country: "Spain", flag: "🇪🇸", sound: "Cof cof", pron: "koaf-koaf", native: "cof cof", fallback: "koaf koaf" },
                { country: "France", flag: "🇫🇷", sound: "Toux", pron: "toooah", native: "toux", fallback: "toooah" },
                { country: "Germany", flag: "🇩🇪", sound: "Hust", pron: "hoooahst", native: "hust", fallback: "hoooahst" },
                { country: "Italy", flag: "🇮🇹", sound: "Tosse", pron: "toas-say", native: "tosse", fallback: "toas say" },
                { country: "Russia", flag: "🇷🇺", sound: "Кхе-кхе", pron: "kheh-kheh", native: "кхе кхе", fallback: "kheh kheh" },
                { country: "Thailand", flag: "🇹🇭", sound: "แค่กแค่ก", pron: "kah-ek", native: "แค่กแค่ก", fallback: "kah ek" },
                { country: "Egypt", flag: "🇪🇬", sound: "كحة", pron: "ko-hah", native: "كحة", fallback: "ko hah" },
                { country: "Brazil", flag: "🇧🇷", sound: "Cof cof", pron: "koaf-koaf", native: "cof cof", fallback: "koaf koaf" },
                { country: "China", flag: "🇨🇳", sound: "咳咳", pron: "keh-keh", native: "咳咳", fallback: "keh keh" },
                { country: "India", flag: "🇮🇳", sound: "खांसी", pron: "khahn-see", native: "खांसी", fallback: "khahn see" },
                { country: "Kenya", flag: "🇰🇪", sound: "Kohoa", pron: "ko-ho", native: "kohoa", fallback: "ko ho" },
                { country: "Greece", flag: "🇬🇷", sound: "Βήχας", pron: "vee-khahs", native: "βήχας", fallback: "cough" }
            ]},
            snore: { id: 'snore', icon: "😴", name: "Snoring", params: { pitch: 0.6, rate: 0.7 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Zzz", pron: "zeee-zeee", native: "zzz", fallback: "zzz" },
                { country: "Korea", flag: "🇰🇷", sound: "드르렁", pron: "deu-reu", native: "드르렁", fallback: "deu reu" },
                { country: "Japan", flag: "🇯🇵", sound: "グーグー", pron: "gooo-gooo", native: "グーグー", fallback: "gooo gooo" },
                { country: "Spain", flag: "🇪🇸", sound: "Ronc", pron: "roahnk", native: "ronc", fallback: "roahnk" },
                { country: "France", flag: "🇫🇷", sound: "Ron pchi", pron: "roahn-pchee", native: "ron pchi", fallback: "roahn pchee" },
                { country: "Germany", flag: "🇩🇪", sound: "Chrr", pron: "chrrr", native: "chrr", fallback: "chrrr" },
                { country: "Italy", flag: "🇮🇹", sound: "Ronf", pron: "roahnf", native: "ronf", fallback: "roahnf" },
                { country: "Russia", flag: "🇷🇺", sound: "Хр-р", pron: "khrrrr", native: "хр р", fallback: "khrrrr" },
                { country: "Thailand", flag: "🇹🇭", sound: "ฟี้", pron: "feee", native: "ฟี้", fallback: "feee" },
                { country: "Egypt", flag: "🇪🇬", sound: "شخير", pron: "shah-keer", native: "شخير", fallback: "shah keer" },
                { country: "Brazil", flag: "🇧🇷", sound: "Ronc", pron: "roahnk", native: "ronc", fallback: "roahnk" },
                { country: "China", flag: "🇨🇳", sound: "呼噜", pron: "hoo-loo", native: "呼噜", fallback: "hoo loo" },
                { country: "India", flag: "🇮🇳", sound: "खर्राटा", pron: "khahr", native: "खर्राटा", fallback: "khahr" },
                { country: "Kenya", flag: "🇰🇪", sound: "Koroma", pron: "ko-ro", native: "koroma", fallback: "ko ro" },
                { country: "Greece", flag: "🇬🇷", sound: "Ροχαλητό", pron: "ro-khah", native: "ροχαλητό", fallback: "snore" }
            ]},
            sigh: { id: 'sigh', icon: "😮‍💨", name: "Sigh", params: { pitch: 0.9, rate: 0.8 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Phew", pron: "f-yoooah", native: "phew", fallback: "f yoooah" },
                { country: "Korea", flag: "🇰🇷", sound: "후", pron: "hoooah", native: "후", fallback: "hoooah" },
                { country: "Japan", flag: "🇯🇵", sound: "ハー", pron: "haah", native: "ハー", fallback: "haah" },
                { country: "Spain", flag: "🇪🇸", sound: "Uf", pron: "ooahf", native: "uf", fallback: "ooahf" },
                { country: "France", flag: "🇫🇷", sound: "Ouf", pron: "ooahf", native: "ouf", fallback: "ooahf" },
                { country: "Germany", flag: "🇩🇪", sound: "Seufz", pron: "zoooahfz", native: "seufz", fallback: "zoooahfz" },
                { country: "Italy", flag: "🇮🇹", sound: "Uff", pron: "ooahf", native: "uff", fallback: "ooahf" },
                { country: "Russia", flag: "🇷🇺", sound: "Ох", pron: "oakh", native: "ох", fallback: "oakh" },
                { country: "Thailand", flag: "🇹🇭", sound: "เฮ้อ", pron: "huhr", native: "เฮ้อ", fallback: "huhr" },
                { country: "Egypt", flag: "🇪🇬", sound: "آه", pron: "aah", native: "آه", fallback: "aah" },
                { country: "Brazil", flag: "🇧🇷", sound: "Ufa", pron: "oo-fah", native: "ufa", fallback: "oo fah" },
                { country: "China", flag: "🇨🇳", sound: "唉", pron: "aye", native: "唉", fallback: "aye" },
                { country: "India", flag: "🇮🇳", sound: "आह", pron: "aah", native: "आह", fallback: "aah" },
                { country: "Kenya", flag: "🇰🇪", sound: "He", pron: "heah", native: "he", fallback: "heah" },
                { country: "Greece", flag: "🇬🇷", sound: "Αχ", pron: "ahkh", native: "αχ", fallback: "ahkh" }
            ]},
            gulp: { id: 'gulp', icon: "🥛", name: "Gulping", params: { pitch: 1.0, rate: 1.1 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Gulp", pron: "gahmpt", native: "gulp", fallback: "gahmpt" },
                { country: "Korea", flag: "🇰🇷", sound: "꿀꺽", pron: "kkool-kkeahk", native: "꿀꺽", fallback: "kkool kkeahk" },
                { country: "Japan", flag: "🇯🇵", sound: "ゴクゴク", pron: "go-koo", native: "ゴクゴク", fallback: "go koo" },
                { country: "Spain", flag: "🇪🇸", sound: "Glup", pron: "glooahmpt", native: "glup", fallback: "glooahmpt" },
                { country: "France", flag: "🇫🇷", sound: "Glou glou", pron: "gloo-gloo", native: "glou glou", fallback: "gloo gloo" },
                { country: "Germany", flag: "🇩🇪", sound: "Schluck", pron: "shlooak", native: "schluck", fallback: "shlooak" },
                { country: "Italy", flag: "🇮🇹", sound: "Gulp", pron: "gahmpt", native: "gulp", fallback: "gahmpt" },
                { country: "Russia", flag: "🇷🇺", sound: "Глоток", pron: "glo-toak", native: "глоток", fallback: "glo toak" },
                { country: "Thailand", flag: "🇹🇭", sound: "อึก", pron: "oo-ak", native: "อึก", fallback: "oo ak" },
                { country: "Egypt", flag: "🇪🇬", sound: "جرعة", pron: "jo-rah", native: "جرعة", fallback: "jo rah" },
                { country: "Brazil", flag: "🇧🇷", sound: "Gole", pron: "go-lee", native: "gole", fallback: "go lee" },
                { country: "China", flag: "🇨🇳", sound: "咕嘟", pron: "goo-doo", native: "咕嘟", fallback: "goo doo" },
                { country: "India", flag: "🇮🇳", sound: "घूंट", pron: "ghoo-nt", native: "घूंट", fallback: "ghoo nt" },
                { country: "Kenya", flag: "🇰🇪", sound: "Gulp", pron: "gahmpt", native: "gulp", fallback: "gahmpt" },
                { country: "Greece", flag: "🇬🇷", sound: "Γουλιά", pron: "ghoo-lyah", native: "γουλιά", fallback: "glup" }
            ]},
            slurp: { id: 'slurp', icon: "🍜", name: "Slurping", params: { pitch: 1.1, rate: 1.3 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Slurp", pron: "sloooahrp", native: "slurp", fallback: "sloooahrp" },
                { country: "Korea", flag: "🇰🇷", sound: "후루룩", pron: "hoo-roo-rook", native: "후루룩", fallback: "hoo roo rook" },
                { country: "Japan", flag: "🇯🇵", sound: "ズルズル", pron: "zoo-roo", native: "ズルズル", fallback: "zoo roo" },
                { country: "Spain", flag: "🇪🇸", sound: "Sorbo", pron: "soar-boah", native: "sorbo", fallback: "soar boah" },
                { country: "France", flag: "🇫🇷", sound: "Slurp", pron: "sloooahrp", native: "slurp", fallback: "sloooahrp" },
                { country: "Germany", flag: "🇩🇪", sound: "Schlürf", pron: "shlooahrf", native: "schlürf", fallback: "shlooahrf" },
                { country: "Italy", flag: "🇮🇹", sound: "Slurp", pron: "sloooahrp", native: "slurp", fallback: "sloooahrp" },
                { country: "Russia", flag: "🇷🇺", sound: "Хлюп", pron: "khlyooap", native: "хлюп", fallback: "khlyooap" },
                { country: "Thailand", flag: "🇹🇭", sound: "ซูด", pron: "soooahd", native: "ซูด", fallback: "soooahd" },
                { country: "Egypt", flag: "🇪🇬", sound: "رشفة", pron: "rah-sh", native: "رشفة", fallback: "rah sh" },
                { country: "Brazil", flag: "🇧🇷", sound: "Slurp", pron: "sloooahrp", native: "slurp", fallback: "sloooahrp" },
                { country: "China", flag: "🇨🇳", sound: "呼噜", pron: "hoo-loo", native: "呼噜", fallback: "hoo loo" },
                { country: "India", flag: "🇮🇳", sound: "सुड़कना", pron: "soo-dahk", native: "सुड़क나", fallback: "soo dahk" },
                { country: "Kenya", flag: "🇰🇪", sound: "Slurp", pron: "sloooahrp", native: "slurp", fallback: "sloooahrp" },
                { country: "Greece", flag: "🇬🇷", sound: "Ρούφηγμα", pron: "roo-feeg", native: "ρούφηγμα", fallback: "slurp" }
            ]},
            clap: { id: 'clap', icon: "👏", name: "Clapping", params: { pitch: 1.2, rate: 1.4 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Clap", pron: "klahp", native: "clap", fallback: "klahp" },
                { country: "Korea", flag: "🇰🇷", sound: "짝짝", pron: "jjak-jjak", native: "짝짝", fallback: "jjak jjak" },
                { country: "Japan", flag: "🇯🇵", sound: "パチパチ", pron: "pah-chee", native: "パチパチ", fallback: "pah chee" },
                { country: "Spain", flag: "🇪🇸", sound: "Plas plas", pron: "plahs-plahs", native: "plas plas", fallback: "plahs plahs" },
                { country: "France", flag: "🇫🇷", sound: "Clap clap", pron: "klahp-klahp", native: "clap clap", fallback: "klahp klahp" },
                { country: "Germany", flag: "🇩🇪", sound: "Klatsch", pron: "klahtsh", native: "klatsch", fallback: "klahtsh" },
                { country: "Italy", flag: "🇮🇹", sound: "Applauso", pron: "ap-plah-oo", native: "applauso", fallback: "ap plah oo" },
                { country: "Russia", flag: "🇷🇺", sound: "Хлоп-хлоп", pron: "khloahp", native: "хлоп хлоп", fallback: "khloahp" },
                { country: "Thailand", flag: "🇹🇭", sound: "แปะแปะ", pron: "pah-ae", native: "แปะแปะ", fallback: "pah ae" },
                { country: "Egypt", flag: "🇪🇬", sound: "تصفيق", pron: "tah-s-feeq", native: "تصفيق", fallback: "tah s feeq" },
                { country: "Brazil", flag: "🇧🇷", sound: "Palma", pron: "pahl-mah", native: "palma", fallback: "pahl mah" },
                { country: "China", flag: "🇨🇳", sound: "啪啪", pron: "pah-pah", native: "啪啪", fallback: "pah pah" },
                { country: "India", flag: "🇮🇳", sound: "ताली", pron: "tah-lee", native: "ताली", fallback: "tah lee" },
                { country: "Kenya", flag: "🇰🇪", sound: "Makofi", pron: "mah-ko-fee", native: "makofi", fallback: "mah ko fee" },
                { country: "Greece", flag: "🇬🇷", sound: "Παλαμάκια", pron: "pah-lah-mah", native: "παλαμάκια", fallback: "clap clap" }
            ]},
            kiss: { id: 'kiss', icon: "💋", name: "Kiss", params: { pitch: 1.3, rate: 1.2 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Smooch", pron: "smoooahch", native: "smooch", fallback: "smoooahch" },
                { country: "Korea", flag: "🇰🇷", sound: "쪽", pron: "jjoahk", native: "쪽", fallback: "jjoahk" },
                { country: "Japan", flag: "🇯🇵", sound: "チュッ", pron: "choo-oo", native: "チュッ", fallback: "choo oo" },
                { country: "Spain", flag: "🇪🇸", sound: "Mua", pron: "moo-ah", native: "mua", fallback: "moo ah" },
                { country: "France", flag: "🇫🇷", sound: "Bisou", pron: "bee-zoo", native: "bisou", fallback: "bee zoo" },
                { country: "Germany", flag: "🇩🇪", sound: "Schmatz", pron: "sh-mahts", native: "schmatz", fallback: "sh mahts" },
                { country: "Italy", flag: "🇮🇹", sound: "Smack", pron: "smah-ck", native: "smack", fallback: "smah ck" },
                { country: "Russia", flag: "🇷🇺", sound: "Чмок", pron: "chmoak", native: "чмок", fallback: "chmoak" },
                { country: "Thailand", flag: "🇹🇭", sound: "จุ๊บ", pron: "joop", native: "จุ๊บ", fallback: "joop" },
                { country: "Egypt", flag: "🇪🇬", sound: "قبلة", pron: "koob-lah", native: "قبلة", fallback: "koob lah" },
                { country: "Brazil", flag: "🇧🇷", sound: "Beijo", pron: "bay-zho", native: "beijo", fallback: "bay zho" },
                { country: "China", flag: "🇨🇳", sound: "亲亲", pron: "cheen-cheen", native: "亲亲", fallback: "cheen cheen" },
                { country: "India", flag: "🇮🇳", sound: "चुंबन", pron: "choom-ban", native: "चुंबन", fallback: "choom ban" },
                { country: "Kenya", flag: "🇰🇪", sound: "Bususu", pron: "boo-soo-soo", native: "bususu", fallback: "boo soo soo" },
                { country: "Greece", flag: "🇬🇷", sound: "Φιλί", pron: "fee-lee", native: "φιλί", fallback: "smooch" }
            ]},
            walk: { id: 'walk', icon: "👞", name: "Walking", params: { pitch: 0.8, rate: 1.0 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Clomp", pron: "cloahmp", native: "clomp", fallback: "cloahmp" },
                { country: "Korea", flag: "🇰🇷", sound: "뚜벅뚜벅", pron: "ttoo-beoahk", native: "뚜벅뚜벅", fallback: "ttoo beoahk" },
                { country: "Japan", flag: "🇯🇵", sound: "コツコツ", pron: "ko-tsoo", native: "コツコツ", fallback: "ko tsoo" },
                { country: "Spain", flag: "🇪🇸", sound: "Paso a paso", pron: "pah-so", native: "paso a paso", fallback: "pah so" },
                { country: "France", flag: "🇫🇷", sound: "Pas", pron: "pah-s", native: "pas", fallback: "pah s" },
                { country: "Germany", flag: "🇩🇪", sound: "Trapp tratsh", pron: "trahp", native: "trapp tratsh", fallback: "trahp" },
                { country: "Italy", flag: "🇮🇹", sound: "Passo", pron: "pahs-so", native: "passo", fallback: "pahs so" },
                { country: "Russia", flag: "🇷🇺", sound: "Топ-топ", pron: "toap-toap", native: "топ топ", fallback: "toap toap" },
                { country: "Thailand", flag: "🇹🇭", sound: "ต๊ะต่อน", pron: "ta-ton", native: "ต๊ะต่อนยอน", fallback: "ta ton" },
                { country: "Egypt", flag: "🇪🇬", sound: "خطوة", pron: "khoat-wah", native: "خطوة", fallback: "khoat wah" },
                { country: "Brazil", flag: "🇧🇷", sound: "Passo", pron: "pahs-so", native: "passo", fallback: "pahs so" },
                { country: "China", flag: "🇨🇳", sound: "嗒嗒", pron: "dah-dah", native: "嗒嗒", fallback: "dah dah" },
                { country: "India", flag: "🇮🇳", sound: "कदम", pron: "kah-dahm", native: "कदम", fallback: "kah dahm" },
                { country: "Kenya", flag: "🇰🇪", sound: "Hatua", pron: "hah-too-ah", native: "hatua", fallback: "hah too ah" },
                { country: "Greece", flag: "🇬🇷", sound: "Βήμα", pron: "vee-mah", native: "βήμα", fallback: "clomp" }
            ]},
            run: { id: 'run', icon: "🏃", name: "Running", params: { pitch: 0.9, rate: 1.5 }, sounds: [
                { country: "USA", flag: "🇺🇸", sound: "Pitter patter", pron: "pit-ter", native: "pitter patter", fallback: "pit ter" },
                { country: "Korea", flag: "🇰🇷", sound: "타다닥", pron: "tah-dah", native: "타다닥", fallback: "tah dah" },
                { country: "Japan", flag: "🇯🇵", sound: "タッタッタッ", pron: "ta-ta-ta", native: "タッタッタッ", fallback: "tah tah tah" },
                { country: "Spain", flag: "🇪🇸", sound: "Correr", pron: "ko-ray-er", native: "correr", fallback: "ko ray er" },
                { country: "France", flag: "🇫🇷", sound: "Vite", pron: "veet", native: "vite", fallback: "veet" },
                { country: "Germany", flag: "🇩🇪", sound: "Renn", pron: "reh-n", native: "renn", fallback: "rehn" },
                { country: "Italy", flag: "🇮🇹", sound: "Corsa", pron: "koar-sah", native: "corsa", fallback: "koar sah" },
                { country: "Russia", flag: "🇷🇺", sound: "Топ-топ", pron: "toap-toap", native: "топ топ", fallback: "toap toap" },
                { country: "Thailand", flag: "🇹🇭", sound: "วิ่ง", pron: "weeng", native: "วิ่ง", fallback: "weeng" },
                { country: "Egypt", flag: "🇪🇬", sound: "جري", pron: "jar-ee", native: "جري", fallback: "jar ee" },
                { country: "Brazil", flag: "🇧🇷", sound: "Correr", pron: "ko-ray-er", native: "correr", fallback: "ko ray er" },
                { country: "China", flag: "🇨🇳", sound: "啪嗒", pron: "pah-dah", native: "啪嗒", fallback: "pah dah" },
                { country: "India", flag: "🇮🇳", sound: "दौड़", pron: "dah-oo-rd", native: "दौड़", fallback: "dah oo rd" },
                { country: "Kenya", flag: "🇰🇪", sound: "Kimbia", pron: "keem-bee", native: "kimbia", fallback: "keem bee" },
                { country: "Greece", flag: "🇬🇷", sound: "Τρέξιμο", pron: "treh-ksee", native: "τρέξιμο", fallback: "run" }
            ]}
        }
    }
};
